import BernoulliSection10.AffineLog
import BernoulliSection10.EfronStein
import BernoulliSection10.PhysicalRows
import BernoulliSection10.IntegratedHodge
import BernoulliSection10.PacketBoundary
import BernoulliSection10.PacketMultiaffine
import BernoulliSection10.PacketProbability
import BernoulliSection10.PacketFrame
import BernoulliSection10.PacketFrameProbability
import BernoulliSection10.HodgeIntegrability
import BernoulliSection10.EndpointDeterminant
import BernoulliSection10.EndpointExteriorGrowth
import BernoulliSection10.EndpointConditioningGrowth
import BernoulliSection10.EndpointConditioningScale
import BernoulliSection10.HodgeEnvelope
import BernoulliSection10.HodgeFamily
import BernoulliSection10.TensorCornerBound
import BernoulliSection10.HodgeFamilyGrowth
import BernoulliSection10.ProductMarginal
import BernoulliSection10.IntervalHodge
import BernoulliSection10.RowConcentration
import BernoulliSection10.SeamComparison
import BernoulliSection10.PacketComparisonGrowth
import BernoulliSection10.PacketTensorReverse
import BernoulliSection10.PacketReset
import BernoulliSection10.SeamProbability

/-!
# Section 10 axiom audit

This module is an executable audit list for the public mathematical results.
It is deliberately kept in the library so that `lake build` checks both the
declarations and the `#print axioms` commands. The names below follow the
arXiv v1 numbering; atom-law scope is documented in FORMALIZATION_MAP.md.
-/

#print axioms BernoulliSection10.lemma_10_2_rho_lintegral_le
#print axioms BernoulliSection10.lemma_10_2_resampling_integral_le_of_pos
#print axioms BernoulliSection10.lemma_10_2_affineValue_ne_zero_ae
#print axioms BernoulliSection10.corollary_10_3

#print axioms BernoulliSection10.efronStein_fin_product
#print axioms BernoulliSection10.efronStein_maxCenteredDeviation

#print axioms BernoulliSection10.clearedStepCompound_isAffineInPhysicalRow
#print axioms BernoulliSection10.independent_mul_clearedStepCompound_mul_isAffineInPhysicalRow

#print axioms BernoulliSection10.clearedStepCompound_inverse_norm_eq_complement
#print axioms BernoulliSection10.intervalDegreeLog_memLp_two
#print axioms BernoulliSection10.normalizedBlockDet_posLog_inv_lintegral_le
#print axioms BernoulliSection10.normalizedEndpointFactor_detLoss_lintegral_le
#print axioms BernoulliSection10.normalizedEndpointFactor_det_isUnit_ae
#print axioms BernoulliSection10.endpointForwardFamily_posLog_lintegral_le
#print axioms BernoulliSection10.endpointExteriorConstant_log_lintegral_le
#print axioms BernoulliSection10.endpointExteriorConstant_log_lintegral_le_W_log_eW
#print axioms BernoulliSection10.intervalCleared_posLog_lintegral_le
#print axioms BernoulliSection10.oneSiteBDet_posLog_inv_lintegral_explicit_le
#print axioms BernoulliSection10.oneSiteCDet_posLog_inv_lintegral_explicit_le
#print axioms BernoulliSection10.oneSiteHodgeEnvelope_controls_ae
#print axioms BernoulliSection10.oneSiteHodgeEnvelope_lintegral_le
#print axioms BernoulliSection10.oneSiteHodgeEnvelope_memLp_two
#print axioms BernoulliSection10.oneSiteHodgeEnvelope_integrable
#print axioms BernoulliSection10.oneSiteClearedFamily_log_deviation
#print axioms BernoulliSection10.oneSiteMaxHodgeEnvelope_controls_ae
#print axioms BernoulliSection10.oneSiteMaxHodgeEnvelope_lintegral_le
#print axioms BernoulliSection10.oneSiteMaxHodgeEnvelope_memLp_two
#print axioms BernoulliSection10.norm_multiAffineTensorOfFunction_le_of_corner
#print axioms BernoulliSection10.norm_oneSiteClearedFamilyTensor_le
#print axioms BernoulliSection10.posLog_norm_oneSiteClearedFamilyTensor_le_W_log_eW
#print axioms BernoulliSection10.oneSiteClearedFamily_posLog_lintegral_le_explicit
#print axioms BernoulliSection10.oneSiteClearedFamily_posLog_lintegral_le_W_log_eW
#print axioms BernoulliSection10.oneSiteMaxHodgeEnvelope_lintegral_le_W_log_eW
#print axioms BernoulliSection10.intervalMaxHodgeEnvelope_lintegral_le_W_log_eW
#print axioms BernoulliSection10.oneSiteMaxHodgeEnvelope_lintegral_le_explicit
#print axioms BernoulliSection10.intervalMaxHodgeEnvelope_lintegral_le_explicit
#print axioms BernoulliSection10.measurePreserving_pi_restrict_embedding
#print axioms BernoulliSection10.intervalSiteRestriction_measurePreserving
#print axioms BernoulliSection10.intervalHodgeEnvelope_lintegral_le
#print axioms BernoulliSection10.intervalHodgeEnvelope_memLp_two
#print axioms BernoulliSection10.intervalClearedProduct_hodgeLoss_le_ae
#print axioms BernoulliSection10.intervalMaxHodgeEnvelope_lintegral_le
#print axioms BernoulliSection10.intervalMaxHodgeEnvelope_memLp_two
#print axioms BernoulliSection10.intervalClearedProduct_hodgeLoss_le_maxEnvelope_ae
#print axioms BernoulliSection10.lemma_10_5

#print axioms BernoulliSection10.packetCoefficient_log_gramEnergy_pathwise
#print axioms BernoulliSection10.proposition_10_8_integrated_endpoint_comparison
#print axioms BernoulliSection10.packetBoundaryPolynomial_multiaffine_and_ne_zero
#print axioms BernoulliSection10.proposition_10_9
#print axioms BernoulliSection10.packetScalarMatrixCoefficientNorm_bounds_and_pos
#print axioms BernoulliSection10.packetScalarMatrixCoefficientPolynomial_ne_zero
#print axioms BernoulliSection10.packetScalarMatrixCoefficientPolynomial_isAffineInPhysicalRow
#print axioms BernoulliSection10.proposition_10_10_scalar_evaluation
#print axioms BernoulliSection10.proposition_10_10_log_inv_le_tensor_loss
#print axioms BernoulliSection10.exists_squarefree_rademacher_norm_le_eval
#print axioms BernoulliSection10.packetScalarMatrixCoefficientNorm_le_evaluationFactor_mul_tensor
#print axioms BernoulliSection10.packetBoundaryCoefficientTensor_le_reverseFactor_mul_raw
#print axioms BernoulliSection10.abs_log_packetBoundaryCoefficientTensor_sub_raw_le
#print axioms BernoulliSection10.packetScalarCoefficientTensor_posLog_inv_lintegral_le_W_log_eW
#print axioms BernoulliSection10.proposition_10_10_packet_reset

#print axioms BernoulliSection10.abs_log_gramVolume_sub_log_maxExteriorOperatorGrowth_le
#print axioms BernoulliSection10.seam_log_triangle
#print axioms BernoulliSection10.packetSeam_fixed_endpoints
#print axioms BernoulliSection10.proposition_10_7_periodic_seam
