import BernoulliSection10.AnchorScales
import BernoulliSection10.AsymptoticErrors
import BernoulliSection10.AsymptoticScales
import BernoulliSection10.CellDimensionLimit
import BernoulliSection10.CircularLawFromPotential
import BernoulliSection10.ClearedSingularTest
import BernoulliSection10.ConcentrationScale
import BernoulliSection10.ConcretePressure
import BernoulliSection10.ConditionalReset
import BernoulliSection10.CutoffRemoval
import BernoulliSection10.CyclicEntryGeometry
import BernoulliSection10.CyclicPhysicalModel
import BernoulliSection10.CyclicPressureComparison
import BernoulliSection10.CyclicSeamAssembly
import BernoulliSection10.CyclicStitchedPressure
import BernoulliSection10.DensityCircularLaw
import BernoulliSection10.DensityEnergyLimit
import BernoulliSection10.DensityPressureLimit
import BernoulliSection10.DiagonalDiskReference
import BernoulliSection10.DimensionReplacement
import BernoulliSection10.DiskReferenceLaw
import BernoulliSection10.ExteriorFrameRelabel
import BernoulliSection10.ExteriorSingularFrames
import BernoulliSection10.FiniteIIDCoordinates
import BernoulliSection10.FiniteIIDLawOfLargeNumbers
import BernoulliSection10.FinitePressure
import BernoulliSection10.FullBlockHighBandProfile
import BernoulliSection10.IntervalConcatenation
import BernoulliSection10.IntervalMeanHodge
import BernoulliSection10.IntervalRestriction
import BernoulliSection10.IntervalTransfer
import BernoulliSection10.LongPressureError
import BernoulliSection10.LongRingLimit
import BernoulliSection10.MeanStitching
import BernoulliSection10.OutsidePressureIdentification
import BernoulliSection10.PacketLawTransport
import BernoulliSection10.PacketPhysicalIdentification
import BernoulliSection10.PhysicalAtomEnergy
import BernoulliSection10.PhysicalBoundaryExpression
import BernoulliSection10.PhysicalIIDEmbedding
import BernoulliSection10.PhysicalInputLaw
import BernoulliSection10.PhysicalMatrixEntries
import BernoulliSection10.PhysicalPacketReset
import BernoulliSection10.PhysicalProbabilityInstances
import BernoulliSection10.PhysicalProfile
import BernoulliSection10.PhysicalReplacement
import BernoulliSection10.PhysicalSeam
import BernoulliSection10.PositiveMatrixIndex
import BernoulliSection10.PressureCalibration
import BernoulliSection10.ProbabilityLimits
import BernoulliSection10.ProbabilityTransport
import BernoulliSection10.ProfileMoments
import BernoulliSection10.ReferenceTruncation
import BernoulliSection10.RemainderControl
import BernoulliSection10.RemainderL1
import BernoulliSection10.RemainderProbability
import BernoulliSection10.ResetSandwichLaw
import BernoulliSection10.SandwichIntegrability
import BernoulliSection10.ScalarBandGeometry
import BernoulliSection10.ScalarReferenceProfile
import BernoulliSection10.Section3Bulk
import BernoulliSection10.Section3Counting
import BernoulliSection10.Section3HardEdge
import BernoulliSection10.Section3Inputs
import BernoulliSection10.SingularCoefficient
import BernoulliSection10.SingularFrames
import BernoulliSection10.SpectralLimitAssembly
import BernoulliSection10.StitchedPressure
import BernoulliSection10.TargetRingLimit
import BernoulliSection10.VarianceProfiles
import BernoulliSection10.WeakCircularLaw

/-!
Complete continuation theorem audit. Each new public theorem is listed explicitly.
The checker requires one exact report for every command and permits only
`propext`, `Classical.choice`, and `Quot.sound`.
-/

-- BernoulliSection10.AnchorScales
#print axioms BernoulliSection10.sqrt_width_times_length_div_dimension_le
#print axioms BernoulliSection10.densitySqrtWidth_div_anchor_le
#print axioms BernoulliSection10.densityCore_fluctuation_div_anchor_le
#print axioms BernoulliSection10.tendsto_densityAnchorSize
#print axioms BernoulliSection10.tendsto_densityAnchor_seam_scale
#print axioms BernoulliSection10.tendsto_densityAnchor_fluctuation_scale

-- BernoulliSection10.AsymptoticErrors
#print axioms BernoulliSection10.density_rpow_ratio
#print axioms BernoulliSection10.densityWidth_div_anchor_le
#print axioms BernoulliSection10.densityAnchor_div_long_dimension_le
#print axioms BernoulliSection10.densityWidth_div_long_dimension_le
#print axioms BernoulliSection10.densitySqrtWidth_div_long_dimension_le
#print axioms BernoulliSection10.densityTargetErrorScale_nonneg
#print axioms BernoulliSection10.densityTargetErrorScale_le
#print axioms BernoulliSection10.tendsto_densityTargetErrorScale
#print axioms BernoulliSection10.tendsto_densityRemainderErrorScale

-- BernoulliSection10.AsymptoticScales
#print axioms BernoulliSection10.densityCellSites_pos
#print axioms BernoulliSection10.densityCoreSites_pos
#print axioms BernoulliSection10.densityAnchorSize_pos
#print axioms BernoulliSection10.rpow_le_densityCellSites
#print axioms BernoulliSection10.densityCellSites_le_five_mul_rpow
#print axioms BernoulliSection10.rpow_anchor_exponent
#print axioms BernoulliSection10.rpow_le_densityAnchorSize
#print axioms BernoulliSection10.densityAnchorSize_le_five_mul_rpow
#print axioms BernoulliSection10.densityRemainderSites_lt
#print axioms BernoulliSection10.densityRemainderSites_eq_sub
#print axioms BernoulliSection10.densityCell_partition
#print axioms BernoulliSection10.densityCell_dimension_ratio
#print axioms BernoulliSection10.densityLogScale_eq
#print axioms BernoulliSection10.densityLogScale_nonneg
#print axioms BernoulliSection10.tendsto_densityLogScale_div_rpow
#print axioms BernoulliSection10.density_direct_highBand
#print axioms BernoulliSection10.eventually_density_anchor_highBand

-- BernoulliSection10.CellDimensionLimit
#print axioms BernoulliSection10.densityCell_dimension_defect_bounds
#print axioms BernoulliSection10.tendsto_densityCell_dimension_ratio

-- BernoulliSection10.CircularLawFromPotential
#print axioms BernoulliSection10.DiskReference.tendstoInMeasure_prod_fst_iff
#print axioms BernoulliSection10.DiskReference.tendstoInMeasure_prod_snd_iff
#print axioms BernoulliSection10.DiskReference.physical_circularLaw_of_logPotential

-- BernoulliSection10.ClearedSingularTest
#print axioms BernoulliSection10.exists_cleared_exterior_product_scalar_test
#print axioms BernoulliSection10.interval_product_scalar_test_ae

-- BernoulliSection10.ConcentrationScale
#print axioms BernoulliSection10.log_three_width_bounds
#print axioms BernoulliSection10.sqrt_physicalRowResamplingEnergy_le
#print axioms BernoulliSection10.densityConcentrationConstant_nonneg
#print axioms BernoulliSection10.intervalPressureConcentrationCost_le

-- BernoulliSection10.ConcretePressure
#print axioms BernoulliSection10.measurable_finitePressureMax
#print axioms BernoulliSection10.integrable_finitePressureMax
#print axioms BernoulliSection10.finitePressureMax_sub_meanMax_le
#print axioms BernoulliSection10.densityOptimizingDegree_maximizes
#print axioms BernoulliSection10.densityOptimizingDegree_minimal
#print axioms BernoulliSection10.intervalDegreeLog_integrable
#print axioms BernoulliSection10.intervalMaxDegreeLog_integrable
#print axioms BernoulliSection10.intervalMaxDegreeLog_sub_maxPressure_integral_le

-- BernoulliSection10.ConditionalReset
#print axioms BernoulliSection10.densityCellMeanErrorConstant_nonneg
#print axioms BernoulliSection10.resetSandwichDegreeLog_integral_bounds_ae

-- BernoulliSection10.CutoffRemoval
#print axioms BernoulliSection10.measure_tendsto_zero_of_energy_cutoffs
#print axioms BernoulliSection10.exp_neg_sourceHardEdgeScale

-- BernoulliSection10.CyclicEntryGeometry
#print axioms BernoulliSection10.cyclicSiteSucc_val
#print axioms BernoulliSection10.cyclicSiteSucc_twice_ne_self
#print axioms BernoulliSection10.cyclic_three_positions_distinct
#print axioms BernoulliSection10.cyclicShift_inv_eq_permMatrix
#print axioms BernoulliSection10.siteBlockDiagonal_mul_cyclicShift_inv_apply
#print axioms BernoulliSection10.physicalCyclicMatrix_entry
#print axioms BernoulliSection10.physicalCyclicMatrix_entry_norm_sq
#print axioms BernoulliSection10.physicalCyclicMatrix_squared_entry_sum

-- BernoulliSection10.CyclicPhysicalModel
#print axioms BernoulliSection10.polynomialClearedCompoundProduct_eq_reverse
#print axioms BernoulliSection10.polynomialClearedCompoundProduct_physicalIntervalSteps
#print axioms BernoulliSection10.densityShiftedCyclicMatrix_eq_sub_scalar
#print axioms BernoulliSection10.densityCyclicLogDet_eq_polynomial_trace

-- BernoulliSection10.CyclicPressureComparison
#print axioms BernoulliSection10.cyclicPressure_L1_bound
#print axioms BernoulliSection10.cyclicPressure_normalized_L1_bound

-- BernoulliSection10.CyclicSeamAssembly
#print axioms BernoulliSection10.measurable_densityCyclicLogDet
#print axioms BernoulliSection10.integrable_prod_of_nonneg_fiber_bound
#print axioms BernoulliSection10.measurable_cyclicSeamDifference
#print axioms BernoulliSection10.cyclicSeamDifference_integrable_and_L1_bound
#print axioms BernoulliSection10.densityCyclicLogDet_integrable

-- BernoulliSection10.CyclicStitchedPressure
#print axioms BernoulliSection10.cyclicStitchedPressure_L1_bound
#print axioms BernoulliSection10.cyclicStitchedPressure_normalized_L1_bound

-- BernoulliSection10.DensityCircularLaw
#print axioms BernoulliSection10.density_profile_circular_law
#print axioms BernoulliSection10.density_circular_law

-- BernoulliSection10.DensityEnergyLimit
#print axioms BernoulliSection10.intervalMeanAtomSquare_tendsto_of_second_moment
#print axioms BernoulliSection10.density_ring_energy_limit_of_second_moment
#print axioms BernoulliSection10.density_ring_energy_limit

-- BernoulliSection10.DensityPressureLimit
#print axioms BernoulliSection10.density_high_band_ring_log_limit
#print axioms BernoulliSection10.densityCorePressureDensity_limit

-- BernoulliSection10.DiagonalDiskReference
#print axioms BernoulliSection10.DiskReference.diagonalDiskReference_measurable
#print axioms BernoulliSection10.DiskReference.realEsdTest_diagonal
#print axioms BernoulliSection10.DiskReference.diagonalDiskReference_energy_eq
#print axioms BernoulliSection10.DiskReference.circularMeasure_norm_sq_integrable
#print axioms BernoulliSection10.DiskReference.diagonalDiskReference_energy_integrable_and_le_one
#print axioms BernoulliSection10.DiskReference.diagonalDiskReference_logPotential_ae
#print axioms BernoulliSection10.DiskReference.diagonalDiskReference_logPotential_limit
#print axioms BernoulliSection10.DiskReference.diagonalDiskReference_esd_limit
#print axioms BernoulliSection10.DiskReference.diagonalDiskReference_logPotential_limit_sequence
#print axioms BernoulliSection10.DiskReference.diagonalDiskReference_esd_limit_sequence

-- BernoulliSection10.DimensionReplacement
#print axioms BernoulliSection10.DimensionReplacement.integral_weighted_logDetDifference_closedBall_sequence
#print axioms BernoulliSection10.DimensionReplacement.smoothEsdDifference_sequence
#print axioms BernoulliSection10.DimensionReplacement.vague_sequence_of_smooth
#print axioms BernoulliSection10.DimensionReplacement.taoVuReplacementPrinciple_sequence

-- BernoulliSection10.DiskReferenceLaw
#print axioms BernoulliSection10.DiskReference.integral_circularMeasure
#print axioms BernoulliSection10.DiskReference.integrable_circularMeasure_iff
#print axioms BernoulliSection10.DiskReference.circularMeasure_log_integrable
#print axioms BernoulliSection10.DiskReference.circularMeasure_log_potential
#print axioms BernoulliSection10.DiskReference.circularMeasure_norm_lt_one
#print axioms BernoulliSection10.DiskReference.circularSample_eval
#print axioms BernoulliSection10.DiskReference.circularSample_average_tendsto

-- BernoulliSection10.ExteriorFrameRelabel
#print axioms BernoulliSection10.unitary_submatrix_columns
#print axioms BernoulliSection10.exists_unitary_exterior_column_relabel
#print axioms BernoulliSection10.exists_unitary_exterior_coefficient_relabel

-- BernoulliSection10.ExteriorSingularFrames
#print axioms BernoulliSection10.exists_positive_exterior_singular_frames
#print axioms BernoulliSection10.norm_exterior_singular_diagonal
#print axioms BernoulliSection10.exists_top_exterior_singular_frame

-- BernoulliSection10.FiniteIIDCoordinates
#print axioms BernoulliSection10.measurePreserving_iid_uncurry
#print axioms BernoulliSection10.measurePreserving_iid_curry
#print axioms BernoulliSection10.measurePreserving_iid_sum_elim
#print axioms BernoulliSection10.measurePreserving_iid_sum_split
#print axioms BernoulliSection10.measurePreserving_iid_reindex

-- BernoulliSection10.FiniteIIDLawOfLargeNumbers
#print axioms BernoulliSection10.measurePreserving_initialIIDCoordinates
#print axioms BernoulliSection10.iid_average_tendsto_ae
#print axioms BernoulliSection10.finiteIID_average_tendsto_in_probability

-- BernoulliSection10.FinitePressure
#print axioms BernoulliSection10.le_finitePressureMax
#print axioms BernoulliSection10.finitePressureMax_le
#print axioms BernoulliSection10.finitePressureMax_attained
#print axioms BernoulliSection10.mem_pressureMaximizers
#print axioms BernoulliSection10.pressureMaximizers_nonempty
#print axioms BernoulliSection10.pressureOptimizingDegree_maximizes
#print axioms BernoulliSection10.pressureOptimizingDegree_le
#print axioms BernoulliSection10.finitePressureMax_mono
#print axioms BernoulliSection10.abs_finitePressureMax_sub_le
#print axioms BernoulliSection10.abs_finitePressureMax_sub_le_max_deviation
#print axioms BernoulliSection10.finitePressureMax_const
#print axioms BernoulliSection10.finitePressureMax_add_const
#print axioms BernoulliSection10.finitePressureMax_mul_nonneg

-- BernoulliSection10.FullBlockHighBandProfile
#print axioms BernoulliSection10.SourceInputs.fullBlockHighBand_profile_log_limit

-- BernoulliSection10.IntervalConcatenation
#print axioms BernoulliSection10.intervalConcat_measurePreserving
#print axioms BernoulliSection10.intervalConcatCoordinate_prefix
#print axioms BernoulliSection10.intervalConcatCoordinate_suffix
#print axioms BernoulliSection10.intervalRestriction_concat_prefix
#print axioms BernoulliSection10.intervalRestriction_concat_suffix
#print axioms BernoulliSection10.intervalClearedProduct_concat

-- BernoulliSection10.IntervalMeanHodge
#print axioms BernoulliSection10.intervalMaxHodgeEnvelope_integral_le
#print axioms BernoulliSection10.abs_intervalDegreeLog_le_maxEnvelope_ae
#print axioms BernoulliSection10.abs_intervalDegreeLog_integral_le
#print axioms BernoulliSection10.abs_intervalPressure_le

-- BernoulliSection10.IntervalRestriction
#print axioms BernoulliSection10.intervalRowEmbedding_rowIndex
#print axioms BernoulliSection10.intervalRestriction_measurePreserving
#print axioms BernoulliSection10.intervalSiteBlocks_intervalRestriction
#print axioms BernoulliSection10.list_ofFn_fin_rev
#print axioms BernoulliSection10.reverseMatrixProduct_split
#print axioms BernoulliSection10.intervalClearedProduct_split

-- BernoulliSection10.IntervalTransfer
#print axioms BernoulliSection10.list_prod_smul_compound
#print axioms BernoulliSection10.intervalClearedProduct_eq_clearing_smul_compound
#print axioms BernoulliSection10.intervalClearingFactor_ne_zero
#print axioms BernoulliSection10.intervalTransferProduct_det_isUnit
#print axioms BernoulliSection10.intervalTransfer_representation_ae

-- BernoulliSection10.LongPressureError
#print axioms BernoulliSection10.cyclicStitchedPressureError_nonneg
#print axioms BernoulliSection10.cyclicStitchedPressureError_div_le
#print axioms BernoulliSection10.tendsto_cyclicStitchedPressureError_div

-- BernoulliSection10.LongRingLimit
#print axioms BernoulliSection10.density_long_ring_log_limit
#print axioms BernoulliSection10.density_long_profile_log_limit

-- BernoulliSection10.MeanStitching
#print axioms BernoulliSection10.intervalPressure_reset_increment
#print axioms BernoulliSection10.intervalPressure_zero_sites
#print axioms BernoulliSection10.intervalPressure_complete_cells
#print axioms BernoulliSection10.densityCorePressure_mean_stitching

-- BernoulliSection10.OutsidePressureIdentification
#print axioms BernoulliSection10.finitePressureMax_log
#print axioms BernoulliSection10.finitePressureMax_compound_norm
#print axioms BernoulliSection10.intervalMaxDegreeLog_eq_outsidePressure_ae

-- BernoulliSection10.PacketLawTransport
#print axioms BernoulliSection10.endpointAtomsFlatten_measurePreserving
#print axioms BernoulliSection10.packetSourceFlatten_measurePreserving
#print axioms BernoulliSection10.packetSelectedAtom_injective
#print axioms BernoulliSection10.packetPhysicalRows_measurePreserving
#print axioms BernoulliSection10.packetPhysicalRows_apply

-- BernoulliSection10.PacketPhysicalIdentification
#print axioms BernoulliSection10.intervalSiteBlocks_packetPhysicalRows
#print axioms BernoulliSection10.intervalClearedProduct_packetPhysicalRows
#print axioms BernoulliSection10.packetScalarCoefficientEval_eq_physical

-- BernoulliSection10.PhysicalAtomEnergy
#print axioms BernoulliSection10.flattenIntervalAtoms_measurePreserving
#print axioms BernoulliSection10.intervalMeanAtomSquare_eq_flat
#print axioms BernoulliSection10.intervalAtom_measurePreserving
#print axioms BernoulliSection10.intervalMeanAtomSquare_integrable
#print axioms BernoulliSection10.intervalMeanAtomSquare_integral
#print axioms BernoulliSection10.intervalMeanAtomSquare_tendsto_in_probability

-- BernoulliSection10.PhysicalBoundaryExpression
#print axioms BernoulliSection10.continuous_physicalBoundaryExpression
#print axioms BernoulliSection10.physicalIntervalSteps_packetPhysicalRows
#print axioms BernoulliSection10.packetBoundaryEval_eq_physical
#print axioms BernoulliSection10.physicalIntervalSteps_concat
#print axioms BernoulliSection10.polynomialClearedCompoundProduct_append
#print axioms BernoulliSection10.densityCyclicLogDet_terminalPacket

-- BernoulliSection10.PhysicalIIDEmbedding
#print axioms BernoulliSection10.physicalNeighborSite_injective
#print axioms BernoulliSection10.physicalColumn_injective
#print axioms BernoulliSection10.physicalRowsFromSquare_measurePreserving
#print axioms BernoulliSection10.squareIIDFromSequence_measurePreserving
#print axioms BernoulliSection10.physicalRowsFromSequence_measurePreserving

-- BernoulliSection10.PhysicalInputLaw
#print axioms BernoulliSection10.SourceInputs.physicalRowsFromInput_measurePreserving
#print axioms BernoulliSection10.SourceInputs.densityCyclicMatrix_physicalRowsFromInput
#print axioms BernoulliSection10.SourceInputs.normalizedShiftLogDet_physicalProfile
#print axioms BernoulliSection10.SourceInputs.profile_log_converges_iff_physical_rows

-- BernoulliSection10.PhysicalMatrixEntries
#print axioms BernoulliSection10.densityCyclicMatrix_from_square
#print axioms BernoulliSection10.densityCyclicMatrix_from_sequence
#print axioms BernoulliSection10.normalizedPhysicalAtom_norm_sq
#print axioms BernoulliSection10.densityCyclicMatrix_squared_entry_sum
#print axioms BernoulliSection10.densityCyclicMatrix_normalized_energy

-- BernoulliSection10.PhysicalPacketReset
#print axioms BernoulliSection10.continuous_physicalPacketCoefficient
#print axioms BernoulliSection10.measurable_physicalPacketResetLoss
#print axioms BernoulliSection10.physicalPacketCoefficient_ne_zero_ae
#print axioms BernoulliSection10.physicalPacketResetLoss_lintegral_le
#print axioms BernoulliSection10.packetProposition1010WLogConstant_ne_top
#print axioms BernoulliSection10.physicalPacketResetConstant_nonneg
#print axioms BernoulliSection10.physicalPacketResetLoss_integrable
#print axioms BernoulliSection10.physicalPacketResetLoss_integral_le

-- BernoulliSection10.PhysicalProbabilityInstances

-- BernoulliSection10.PhysicalProfile
#print axioms BernoulliSection10.physicalSiteAdjacent_symm
#print axioms BernoulliSection10.physicalProfile_nonnegative
#print axioms BernoulliSection10.physicalProfile_symm
#print axioms BernoulliSection10.blockNormalization_sq
#print axioms BernoulliSection10.physicalProfile_square_three_positions
#print axioms BernoulliSection10.physicalProfile_row
#print axioms BernoulliSection10.physicalProfile_column
#print axioms BernoulliSection10.physicalColumn_adjacent
#print axioms BernoulliSection10.physicalProfile_at_column
#print axioms BernoulliSection10.physicalProfile_sq_le

-- BernoulliSection10.PhysicalReplacement
#print axioms BernoulliSection10.Replacement.normalizedMatrix_undoPhysicalNormalization
#print axioms BernoulliSection10.Replacement.normalizedLogDet_undoPhysicalNormalization
#print axioms BernoulliSection10.Replacement.normalizedEnergy_undoPhysicalNormalization
#print axioms BernoulliSection10.Replacement.tendstoInMeasure_iff_tri
#print axioms BernoulliSection10.Replacement.tendstoInProbabilityTri_neg
#print axioms BernoulliSection10.Replacement.tendstoInMeasure_sub_same_constant
#print axioms BernoulliSection10.Replacement.boundedInProbability_of_uniform_integral
#print axioms BernoulliSection10.Replacement.physical_replacement_of_logPotential_limits

-- BernoulliSection10.PhysicalSeam
#print axioms BernoulliSection10.measurable_physicalSeamLoss
#print axioms BernoulliSection10.physicalBoundaryExpression_ne_zero_ae
#print axioms BernoulliSection10.physicalSeamLoss_lintegral_le
#print axioms BernoulliSection10.packetProposition107WLogConstant_ne_top
#print axioms BernoulliSection10.physicalSeamConstant_nonneg
#print axioms BernoulliSection10.physicalSeamLoss_integrable
#print axioms BernoulliSection10.physicalSeamLoss_integral_le

-- BernoulliSection10.PositiveMatrixIndex
#print axioms BernoulliSection10.positiveMatrixIndex_succ
#print axioms BernoulliSection10.positiveMatrixIndex_log
#print axioms BernoulliSection10.positiveMatrixIndex_energy
#print axioms BernoulliSection10.positiveMatrixIndex_esd
#print axioms BernoulliSection10.measurable_positiveMatrixIndex_entry
#print axioms BernoulliSection10.tendsto_pred_dimension

-- BernoulliSection10.PressureCalibration
#print axioms BernoulliSection10.tendsto_cyclicAnchorPressureError
#print axioms BernoulliSection10.densityCorePressureDensity_tendsto_of_anchor

-- BernoulliSection10.ProbabilityLimits
#print axioms BernoulliSection10.ProbabilityLimits.tendstoInProbabilityTri_of_L1
#print axioms BernoulliSection10.ProbabilityLimits.TendstoInProbabilityTri.congr
#print axioms BernoulliSection10.ProbabilityLimits.TendstoInProbabilityTri.add
#print axioms BernoulliSection10.ProbabilityLimits.tendstoInProbabilityTri_const
#print axioms BernoulliSection10.ProbabilityLimits.deterministic_center_tendsto_of_tri_anchor_and_close
#print axioms BernoulliSection10.ProbabilityLimits.deterministic_center_tendsto_of_tri_anchor_and_L1_close
#print axioms BernoulliSection10.ProbabilityLimits.deterministic_center_tendsto_of_tri_anchor_and_two_L1_seams
#print axioms BernoulliSection10.ProbabilityLimits.tendstoInProbabilityTri_of_center_tendsto_and_L1_close
#print axioms BernoulliSection10.ProbabilityLimits.longBranch_tendstoInProbabilityTri_of_L1_seams
#print axioms BernoulliSection10.ProbabilityLimits.tendstoInProbabilityTri_branchSelected

-- BernoulliSection10.ProbabilityTransport
#print axioms BernoulliSection10.ProbabilityLimits.tendstoInProbabilityTri_measurePreserving_iff

-- BernoulliSection10.ProfileMoments
#print axioms BernoulliSection10.SourceInputs.inputAtom_measurePreserving
#print axioms BernoulliSection10.SourceInputs.measurable_profileMatrix_entry
#print axioms BernoulliSection10.SourceInputs.integrable_profileMatrix_entry
#print axioms BernoulliSection10.SourceInputs.profileMatrix_norm_sq
#print axioms BernoulliSection10.SourceInputs.integrable_profileMatrix_norm_sq
#print axioms BernoulliSection10.SourceInputs.integral_profileMatrix_entry
#print axioms BernoulliSection10.SourceInputs.integral_profileMatrix_norm_sq
#print axioms BernoulliSection10.SourceInputs.profileMatrix_row_moments
#print axioms BernoulliSection10.SourceInputs.profileMatrix_energy_integrable
#print axioms BernoulliSection10.SourceInputs.integral_profileMatrix_energy

-- BernoulliSection10.ReferenceTruncation
#print axioms BernoulliSection10.ReferenceTruncation.positive_singular_eq_on_lsv_good
#print axioms BernoulliSection10.ReferenceTruncation.positive_lower_correction_tendsto
#print axioms BernoulliSection10.ReferenceTruncation.matrix_log_limit_of_reference

-- BernoulliSection10.RemainderControl
#print axioms BernoulliSection10.matrixL2OperatorNorm_le_frobenius
#print axioms BernoulliSection10.matrix_logNorm_mul_bounds
#print axioms BernoulliSection10.abs_matrix_logNorm_mul_sub_le_hodgeLoss
#print axioms BernoulliSection10.intervalClearedProduct_det_isUnit
#print axioms BernoulliSection10.intervalClearedProduct_det_isUnit_ae
#print axioms BernoulliSection10.interval_remainder_log_change_le_ae
#print axioms BernoulliSection10.interval_remainder_max_change_le_ae

-- BernoulliSection10.RemainderL1
#print axioms BernoulliSection10.intervalRemainderMaxDifference_integrable
#print axioms BernoulliSection10.intervalRemainderMaxDifference_L1_bound
#print axioms BernoulliSection10.stitchedPressure_with_remainder_L1_bound

-- BernoulliSection10.RemainderProbability
#print axioms BernoulliSection10.remainderHodgeConstant_nonneg
#print axioms BernoulliSection10.oneSiteMaxHodgeWLogConstant_ne_top
#print axioms BernoulliSection10.intervalMaxHodgeEnvelope_nonneg
#print axioms BernoulliSection10.intervalRemainderMaxDifference_le_ae
#print axioms BernoulliSection10.suffixHodgeEnvelope_integral_le
#print axioms BernoulliSection10.measureReal_abs_ge_le_of_ae_bound
#print axioms BernoulliSection10.intervalRemainderMaxDifference_markov
#print axioms BernoulliSection10.intervalRemainderMaxDifference_normalized_markov
#print axioms BernoulliSection10.intervalRemainderMaxDifference_normalized_tendsto
#print axioms BernoulliSection10.densityRemainder_normalized_tendsto

-- BernoulliSection10.ResetSandwichLaw
#print axioms BernoulliSection10.real_integral_comp_measurePreserving
#print axioms BernoulliSection10.resetSandwichRows_measurePreserving
#print axioms BernoulliSection10.intervalClearedProduct_resetSandwichRows
#print axioms BernoulliSection10.resetSandwichRowsFlat_measurePreserving
#print axioms BernoulliSection10.resetSandwichLog_joint_integrable

-- BernoulliSection10.SandwichIntegrability
#print axioms BernoulliSection10.log_product_lower_of_scalar_test
#print axioms BernoulliSection10.log_norm_sandwich_upper
#print axioms BernoulliSection10.fixed_interval_sandwich_log_integrable

-- BernoulliSection10.ScalarBandGeometry
#print axioms BernoulliSection10.physicalSiteAdjacent_of_val_succ
#print axioms BernoulliSection10.physicalSiteAdjacent_first_last
#print axioms BernoulliSection10.physicalSiteAdjacent_of_ordered_scalar_distance
#print axioms BernoulliSection10.physicalSiteAdjacent_of_scalar_distance
#print axioms BernoulliSection10.physicalProfile_scalar_band_value

-- BernoulliSection10.ScalarReferenceProfile
#print axioms BernoulliSection10.SourceInputs.cyclicColumn_row_injective
#print axioms BernoulliSection10.SourceInputs.scalarIndicatorProfile_nonnegative
#print axioms BernoulliSection10.SourceInputs.scalarIndicatorProfile_sq
#print axioms BernoulliSection10.SourceInputs.scalarIndicatorProfile_doublyStochastic
#print axioms BernoulliSection10.SourceInputs.exists_cyclicColumn_of_scalar_distance
#print axioms BernoulliSection10.SourceInputs.uniformIndicatorProfile_sq_of_active
#print axioms BernoulliSection10.SourceInputs.uniformIndicatorProfile_sq_le
#print axioms BernoulliSection10.SourceInputs.uniformIndicatorProfile_scalar_band

-- BernoulliSection10.Section3Bulk
#print axioms BernoulliSection10.SourceInputs.clippedLogComparison_of_section3

-- BernoulliSection10.Section3Counting
#print axioms BernoulliSection10.SourceInputs.mesoscopicThreshold_le_sourceCutoff_eventually
#print axioms BernoulliSection10.SourceInputs.mesoscopicCountingInput_of_section3

-- BernoulliSection10.Section3HardEdge
#print axioms BernoulliSection10.SourceInputs.leastSingularValueInput_of_section3

-- BernoulliSection10.Section3Inputs

-- BernoulliSection10.SingularCoefficient
#print axioms BernoulliSection10.matrix_entry_norm_le_operatorNorm
#print axioms BernoulliSection10.diagonal_sandwich_coefficient_le
#print axioms BernoulliSection10.singular_sandwich_coefficient_le
#print axioms BernoulliSection10.exists_exterior_product_scalar_test

-- BernoulliSection10.SingularFrames
#print axioms BernoulliSection10.exists_positive_singular_frames

-- BernoulliSection10.SpectralLimitAssembly
#print axioms BernoulliSection10.DiskReference.esd_limit_of_replacement

-- BernoulliSection10.StitchedPressure
#print axioms BernoulliSection10.intervalMaxPressure_complete_cells
#print axioms BernoulliSection10.stitchedPressure_L1_bound
#print axioms BernoulliSection10.stitchedPressure_markov

-- BernoulliSection10.TargetRingLimit
#print axioms BernoulliSection10.densityLongAuxSites_long
#print axioms BernoulliSection10.densityDirectAuxSites_highBand
#print axioms BernoulliSection10.density_profile_log_limit
#print axioms BernoulliSection10.density_ring_log_limit

-- BernoulliSection10.VarianceProfiles
#print axioms BernoulliSection10.SourceInputs.maxEntryVariance_le_of_entry_le
#print axioms BernoulliSection10.SourceInputs.entryVariance_le_maxEntryVariance
#print axioms BernoulliSection10.SourceInputs.physicalProfile_doublyStochastic
#print axioms BernoulliSection10.SourceInputs.maxEntryVariance_physicalProfile
#print axioms BernoulliSection10.SourceInputs.effectiveBandwidth_physicalProfile
#print axioms BernoulliSection10.SourceInputs.physicalProfile_lsv_upper
#print axioms BernoulliSection10.SourceInputs.physicalProfile_lsv_lower
#print axioms BernoulliSection10.SourceInputs.maxEntryVariance_uniformIndicator
#print axioms BernoulliSection10.SourceInputs.effectiveBandwidth_uniformIndicator
#print axioms BernoulliSection10.SourceInputs.uniformIndicator_lsv_upper
#print axioms BernoulliSection10.SourceInputs.uniformIndicator_lsv_lower
#print axioms BernoulliSection10.SourceInputs.scalarReferenceWidth_fit
#print axioms BernoulliSection10.SourceInputs.width_le_scalarReferenceWidth

-- BernoulliSection10.WeakCircularLaw
#print axioms BernoulliSection10.DiskReference.circularTestCutoff_ae_one
#print axioms BernoulliSection10.DiskReference.circularTestCutoff_integral
#print axioms BernoulliSection10.DiskReference.realEsdTest_subtract
#print axioms BernoulliSection10.DiskReference.abs_realEsdTest_sub_le_spectral_error
#print axioms BernoulliSection10.DiskReference.realEsdTest_cutoff_error
#print axioms BernoulliSection10.DiskReference.tendstoInProbabilityTri_of_cutoff_error
#print axioms BernoulliSection10.DiskReference.circularLaw_boundedContinuous_of_compactSupport
#print axioms BernoulliSection10.DiskReference.circularLaw_boundedContinuousMap_of_compactSupport

/- The explicit types expose the complete caller-facing assumption boundary. -/
#print BernoulliSection10.SourceInputs.Section3Inputs
#check @BernoulliSection10.density_high_band_ring_log_limit
#check @BernoulliSection10.densityCorePressureDensity_limit
#check @BernoulliSection10.density_long_ring_log_limit
#check @BernoulliSection10.density_ring_log_limit
#check @BernoulliSection10.density_ring_energy_limit_of_second_moment
#check @BernoulliSection10.density_profile_circular_law
#check @BernoulliSection10.density_circular_law
