name = "RandomBandCircularLaw"
version = "0.1.0"
defaultTargets = ["CircularLawSection4", "BernoulliLinearAlgebra"]

[[lean_lib]]
name = "CircularLawSection4"
srcDir = "Section4"

[[lean_lib]]
name = "BernoulliLinearAlgebra"
srcDir = "Section9"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.33.0"
