name = "CircularLawSection6"
version = "0.1.0"
defaultTargets = ["CircularLawSection6"]
packagesDir = "../.lake/packages"

[[lean_lib]]
name = "CircularLawSection6"

[[require]]
name = "CircularLawSections56"
path = "../section5"
