import CircularLawSection6.VerifiedPointwiseProfileEndpoint
import CircularLawSection6.CoreNormalizationPointwise

/-! Axiom audit for the fixed-shift Section 5/6 route. -/

#print axioms CircularLawSection6.weightedCyclicShiftedDetPolynomial_ne_zero
#print axioms CircularLawSection6.weightedCyclicMatrix_shifted_det_ne_zero
#print axioms CircularLawSection6.NoncompactProfile.gaussian_profile_det_nonzero
#print axioms CircularLawSection6.NoncompactProfile.gaussian_core_det_nonzero
#print axioms CircularLawSection6.NoncompactProfile.gaussian_unitCore_det_nonzero
#print axioms CircularLawSection6.tendsto_zero_everywhere_of_ae_lipschitz
#print axioms CircularLawSection6.expected_matrixCutoff_shift_lipschitz
#print axioms CircularLawSection6.CoreRadiusBounds.canonical_core_cutoff_comparison_of_bbv_at
#print axioms CircularLawSection6.NoncompactProfile.gaussian_core_cutoff_normalization_error_at
#print axioms CircularLawSection6.NoncompactProfile.scaledUnitCoreMean_eq_log_add
#print axioms CircularLawSection6.NoncompactProfile.gaussian_core_raw_mean_of_fixed_scales_at
#print axioms CircularLawSection6.NoncompactProfile.rawCore_mean_of_section5_at
#print axioms CircularLawSection6.NoncompactProfile.gaussian_expected_core_full_cutoff_sandwich_at
#print axioms CircularLawSection6.NoncompactProfile.gaussian_unitCore_cutoff_scaling_at
#print axioms CircularLawSection6.NoncompactProfile.gaussian_expected_unitCore_upper_at
#print axioms CircularLawSection6.CoreRadiusBounds.verifiedClampedLogPotential_at
#print axioms CircularLawSection6.NoncompactProfile.canonical_core_raw_mean_of_eventual_section5_at
#print axioms CircularLawSection6.CoreRadiusBounds.verifiedToCanonicalPointwise
#print axioms CircularLawSection6.ginibre_iterated_cutoff_error_of_bbv_at
#print axioms CircularLawSection6.NoncompactProfile.sparse_profile_mean_of_bbv_section5_at
#print axioms CircularLawSection6.NoncompactProfile.sparse_profile_probability_of_bbv_section5_at
#print axioms CircularLawSection6.tendstoInProbabilityTri_of_sparse_dense_subsequences
#print axioms CircularLawSection6.NoncompactProfile.profile_probability_along_sparse_subsequence_of_bbv_at
#print axioms CircularLawSection6.NoncompactProfile.gaussian_profile_logPotential_of_bbv
#print axioms CircularLawSection6.NoncompactProfile.gaussian_profile_circular_law_of_pointwise_bbv
