import BernoulliLinearAlgebra.BoundaryVolume
import BernoulliLinearAlgebra.MaskCoefficient
import Mathlib.Tactic

/-!
# Terminal coefficients versus Gram volume

This file instantiates `TerminalCoefficientComparison` with the finite mask
expansion from `MaskCoefficient`.  For a matrix `Q`, its terminal coefficient
is the norm of the translated coefficient vector whose zero-shift entries are
weighted square minors of `Q`.

The comparison constant is completely explicit.  It is the maximum of `1`,
the upper mask/translation loss, and the inverse lower mask/translation
factor.  Consequently the result is uniform in `Q`.
-/

open scoped BigOperators Matrix

noncomputable section

namespace BernoulliLinearAlgebra

open Matrix Set Set.powersetCard

section EnergyBridge

variable {n : Type*} [Fintype n] [DecidableEq n] [LinearOrder n]

/-- The `realAllMinorEnergy` used by `VolumeComparison` is the concrete
sigma-indexed square-minor energy used by `MaskCoefficient`.  The proof
passes through both the Gram determinant and the complex all-minor identity,
so the two independently introduced encodings are explicitly identified. -/
theorem realAllMinorEnergy_eq_squareMinorEnergy (Q : Matrix n n ℂ) :
    realAllMinorEnergy Q = squareMinorEnergy Q := by
  calc
    realAllMinorEnergy Q = gramEnergy Q :=
      (gramEnergy_eq_realAllMinorEnergy Q).symm
    _ = (allMinorEnergy Q).re := by
      unfold gramEnergy
      rw [det_one_add_gram_eq_sum_compoundEnergy]
    _ = squareMinorEnergy Q := allMinorEnergy_re_eq_squareMinorEnergy Q

/-- Gram energy is exactly the concrete all-square-minor energy. -/
theorem gramEnergy_eq_squareMinorEnergy (Q : Matrix n n ℂ) :
    gramEnergy Q = squareMinorEnergy Q := by
  rw [gramEnergy_eq_realAllMinorEnergy,
    realAllMinorEnergy_eq_squareMinorEnergy]

/-- The square root of all-square-minor energy is the Gram volume.  This
version is proved from `gramVolume_sq`, making the nonnegative square-root
choice explicit. -/
theorem sqrt_squareMinorEnergy_eq_gramVolume (Q : Matrix n n ℂ) :
    √(squareMinorEnergy Q) = gramVolume Q := by
  apply (sq_eq_sq₀ (Real.sqrt_nonneg _) (gramVolume_nonneg Q)).mp
  rw [Real.sq_sqrt (squareMinorEnergy_nonneg Q), gramVolume_sq,
    gramEnergy_eq_squareMinorEnergy]

end EnergyBridge

section TerminalMask

variable {vars n : Type*}
variable [Fintype vars] [DecidableEq vars]
variable [Fintype n] [DecidableEq n] [LinearOrder n]

/-- The terminal coefficient norm generated by a square-minor mask and a
fixed list of affine coordinate translations. -/
def terminalCoefficient
    (shifts : List (vars × ℂ))
    (f : Finset vars → SquareMinorIndex n)
    (w : Finset vars → ℂ)
    (Q : Matrix n n ℂ) : ℝ :=
  ‖translateCoeffList shifts
    (maskCoeffVector f w (squareMinorValue Q))‖

/-- The coefficient multiplying Gram volume in the lower mask estimate. -/
def terminalLowerFactor
    (shifts : List (vars × ℂ))
    {f : Finset vars → SquareMinorIndex n}
    {w : Finset vars → ℂ}
    (c : MaskExpansionCertificate f w) : ℝ :=
  (translationFactor shifts)⁻¹ * √c.lowerWeight

/-- The coefficient multiplying Gram volume in the upper mask estimate. -/
def terminalUpperFactor
    (shifts : List (vars × ℂ))
    {f : Finset vars → SquareMinorIndex n}
    {w : Finset vars → ℂ}
    (c : MaskExpansionCertificate f w) : ℝ :=
  translationFactor shifts *
    √((c.fiberBound : ℝ) * c.upperWeight)

/-- One common comparison constant.  The third entry is the reciprocal of
the lower estimate, so `K⁻¹` is no larger than `terminalLowerFactor`. -/
def terminalComparisonConstant
    (shifts : List (vars × ℂ))
    {f : Finset vars → SquareMinorIndex n}
    {w : Finset vars → ℂ}
    (c : MaskExpansionCertificate f w) : ℝ :=
  max 1 (max (terminalUpperFactor shifts c)
    (terminalLowerFactor shifts c)⁻¹)

omit [DecidableEq vars] [LinearOrder n] in
theorem terminalLowerFactor_pos
    (shifts : List (vars × ℂ))
    {f : Finset vars → SquareMinorIndex n}
    {w : Finset vars → ℂ}
    (c : MaskExpansionCertificate f w)
    (hLower : 0 < c.lowerWeight) :
    0 < terminalLowerFactor shifts c := by
  unfold terminalLowerFactor
  exact mul_pos (inv_pos.mpr (translationFactor_pos shifts))
    (Real.sqrt_pos.2 hLower)

omit [DecidableEq vars] [LinearOrder n] in
theorem terminalComparisonConstant_one_le
    (shifts : List (vars × ℂ))
    {f : Finset vars → SquareMinorIndex n}
    {w : Finset vars → ℂ}
    (c : MaskExpansionCertificate f w) :
    1 ≤ terminalComparisonConstant shifts c := by
  exact le_max_left _ _

omit [DecidableEq vars] [LinearOrder n] in
theorem terminalComparisonConstant_pos
    (shifts : List (vars × ℂ))
    {f : Finset vars → SquareMinorIndex n}
    {w : Finset vars → ℂ}
    (c : MaskExpansionCertificate f w) :
    0 < terminalComparisonConstant shifts c :=
  zero_lt_one.trans_le (terminalComparisonConstant_one_le shifts c)

omit [DecidableEq vars] [LinearOrder n] in
theorem terminalUpperFactor_le_constant
    (shifts : List (vars × ℂ))
    {f : Finset vars → SquareMinorIndex n}
    {w : Finset vars → ℂ}
    (c : MaskExpansionCertificate f w) :
    terminalUpperFactor shifts c ≤ terminalComparisonConstant shifts c := by
  unfold terminalComparisonConstant
  exact (le_max_left _ _).trans (le_max_right _ _)

omit [DecidableEq vars] [LinearOrder n] in
theorem terminalComparisonConstant_inv_le_lowerFactor
    (shifts : List (vars × ℂ))
    {f : Finset vars → SquareMinorIndex n}
    {w : Finset vars → ℂ}
    (c : MaskExpansionCertificate f w)
    (hLower : 0 < c.lowerWeight) :
    (terminalComparisonConstant shifts c)⁻¹ ≤
      terminalLowerFactor shifts c := by
  apply (inv_le_comm₀ (terminalComparisonConstant_pos shifts c)
    (terminalLowerFactor_pos shifts c hLower)).2
  unfold terminalComparisonConstant
  exact (le_max_right _ _).trans (le_max_right _ _)

/-- Raw lower comparison before replacing its coefficient by the common
constant. -/
theorem terminalLowerFactor_mul_gramVolume_le
    (shifts : List (vars × ℂ))
    (f : Finset vars → SquareMinorIndex n)
    (w : Finset vars → ℂ)
    (c : MaskExpansionCertificate f w)
    (Q : Matrix n n ℂ) :
    terminalLowerFactor shifts c * gramVolume Q ≤
      terminalCoefficient shifts f w Q := by
  have h :=
    (lemma35_squareMinor_mask_translate_norm_bounds shifts Q f w c).1
  rw [allMinorEnergy_re_eq_squareMinorEnergy,
    sqrt_squareMinorEnergy_eq_gramVolume] at h
  simpa [terminalLowerFactor, terminalCoefficient] using h

/-- Raw upper comparison before replacing its coefficient by the common
constant. -/
theorem terminalCoefficient_le_upperFactor_mul_gramVolume
    (shifts : List (vars × ℂ))
    (f : Finset vars → SquareMinorIndex n)
    (w : Finset vars → ℂ)
    (c : MaskExpansionCertificate f w)
    (Q : Matrix n n ℂ) :
    terminalCoefficient shifts f w Q ≤
      terminalUpperFactor shifts c * gramVolume Q := by
  have h :=
    (lemma35_squareMinor_mask_translate_norm_bounds shifts Q f w c).2
  rw [allMinorEnergy_re_eq_squareMinorEnergy,
    sqrt_squareMinorEnergy_eq_gramVolume] at h
  simpa [terminalUpperFactor, terminalCoefficient] using h

/-- Uniform lower comparison with the single explicit constant `K`. -/
theorem terminalComparison_lower
    (shifts : List (vars × ℂ))
    (f : Finset vars → SquareMinorIndex n)
    (w : Finset vars → ℂ)
    (c : MaskExpansionCertificate f w)
    (hLower : 0 < c.lowerWeight)
    (Q : Matrix n n ℂ) :
    (terminalComparisonConstant shifts c)⁻¹ * gramVolume Q ≤
      terminalCoefficient shifts f w Q := by
  calc
    (terminalComparisonConstant shifts c)⁻¹ * gramVolume Q ≤
        terminalLowerFactor shifts c * gramVolume Q := by
      exact mul_le_mul_of_nonneg_right
        (terminalComparisonConstant_inv_le_lowerFactor shifts c hLower)
        (gramVolume_nonneg Q)
    _ ≤ terminalCoefficient shifts f w Q :=
      terminalLowerFactor_mul_gramVolume_le shifts f w c Q

/-- Uniform upper comparison with the same explicit constant `K`. -/
theorem terminalComparison_upper
    (shifts : List (vars × ℂ))
    (f : Finset vars → SquareMinorIndex n)
    (w : Finset vars → ℂ)
    (c : MaskExpansionCertificate f w)
    (Q : Matrix n n ℂ) :
    terminalCoefficient shifts f w Q ≤
      terminalComparisonConstant shifts c * gramVolume Q := by
  calc
    terminalCoefficient shifts f w Q ≤
        terminalUpperFactor shifts c * gramVolume Q :=
      terminalCoefficient_le_upperFactor_mul_gramVolume shifts f w c Q
    _ ≤ terminalComparisonConstant shifts c * gramVolume Q := by
      exact mul_le_mul_of_nonneg_right
        (terminalUpperFactor_le_constant shifts c) (gramVolume_nonneg Q)

/-- Constructor requested by Section 9.5: every certified square-minor mask
with positive lower weight produces a `TerminalCoefficientComparison` valid
for every terminal matrix `Q`. -/
theorem terminalCoefficientComparison
    (shifts : List (vars × ℂ))
    (f : Finset vars → SquareMinorIndex n)
    (w : Finset vars → ℂ)
    (c : MaskExpansionCertificate f w)
    (hLower : 0 < c.lowerWeight) :
    TerminalCoefficientComparison (terminalCoefficient shifts f w)
      (terminalComparisonConstant shifts c) where
  one_le := terminalComparisonConstant_one_le shifts c
  lower := terminalComparison_lower shifts f w c hLower
  upper := terminalComparison_upper shifts f w c

end TerminalMask

end BernoulliLinearAlgebra
