import BernoulliSection10Source.DensityCircularLaw

#print axioms BernoulliSection10Source.normalizedGaussianPair_map
#print axioms BernoulliSection10Source.sequencePairs_measurePreserving
#print axioms BernoulliSection10Source.ginibreOnSequence_hasEntryLaw
#print axioms BernoulliSection10Source.gaussianMatrixEntriesEquiv
#print axioms BernoulliSection10Source.ginibreOnSequence_hasLaw
#print axioms BernoulliSection10Source.sequenceDenseModel
#print axioms BernoulliSection10Source.ginibre_negative_on_sequence_of_bbv
#print axioms BernoulliSection10Source.ginibre_logPotential_on_sequence
#print axioms BernoulliSection10Source.provedGinibreInput
#print axioms BernoulliSection10Source.fullBlock_log_limit_from_source
#print axioms BernoulliSection10Source.planar_highBandLogLimit
#print axioms BernoulliSection10Source.real_highBandLogLimit
#print axioms BernoulliSection10Source.planar_density_circular_law
#print axioms BernoulliSection10Source.real_density_circular_law
#print axioms BernoulliSection10Source.planar_density_ring_log_limit
#print axioms BernoulliSection10Source.real_density_ring_log_limit

-- The signature audit is essential: external theorem parameters do not
-- appear in the kernel-axiom list.
set_option pp.fullNames true
#print BernoulliSection10Source.BBVComparisonInput
#check @BernoulliSection10Source.provedGinibreInput
#print LivshytsProjectionFormalization.RealFiniteGeometricBrascampLieb
#print BernoulliSection10Complex.IsPlanarDensityAtom
#print BernoulliSection10.IsBoundedDensityAtom
#check @BernoulliSection10Source.planar_density_circular_law
#check @BernoulliSection10Source.real_density_circular_law
#check @BernoulliSection10Source.planar_density_ring_log_limit
#check @BernoulliSection10Source.real_density_ring_log_limit
