import CircularLawSections56.Section5.PublishedSection3ConcreteEndpoint
import CircularLawSections56.Section5.TaperVerifiedGinibre

-- Exact reports are checked against the standard three-axiom allowlist in CI.
#print axioms CircularLawSections56.Section5.PublishedSection3Concrete.complexGaussian_pi_toLp
#print axioms CircularLawSections56.Section5.PublishedSection3Concrete.complexGaussian_columns_measurePreserving
#print axioms CircularLawSections56.Section5.PublishedSection3Concrete.normalizedColumnEntries_measurable
#print axioms CircularLawSections56.Section5.PublishedSection3Concrete.normalizedGinibreLaw_eq_map_iidColumns
#print axioms CircularLawSections56.Section5.PublishedSection3Concrete.sequenceColumns_measurePreserving
#print axioms CircularLawSections56.Section5.PublishedSection3Concrete.ginibreOnSequence_hasLaw
#print axioms CircularLawSections56.Section5.PublishedSection3Concrete.sequenceDenseModel
#print axioms CircularLawSections56.Section5.PublishedSection3Concrete.ginibre_negative_on_sequence_of_bbv
#print axioms CircularLawSections56.Section5.PublishedSection3Concrete.ginibre_logPotential_on_sequence
#print axioms CircularLawSections56.Section5.PublishedSection3Concrete.provedGinibreInput
#print axioms CircularLawSections56.Section5.Section3TaperNonGaussianInputs.toAnalytic
#print axioms CircularLawSections56.Section5.tapered_short_ring_of_section3_estimates_withoutBC12
#print axioms CircularLawSections56.Section5.PublishedSection3Concrete.concreteModel_sources
#print axioms CircularLawSections56.Section5.PublishedSection3Concrete.literal_anchors
#print axioms CircularLawSections56.Section5.PublishedSection3Concrete.indicator_complex_full_of_published_literature
#print axioms CircularLawSections56.Section5.PublishedSection3Concrete.indicator_real_full_of_published_literature

-- The compatibility proposition is constructed with only the BBV premise.
example (h : CircularLawSections56.Section5.PublishedSection3Concrete.BBVComparisonInput) :
    CircularLawSections56.Section5.PublishedSection3Concrete.BC12GinibreInput :=
  CircularLawSections56.Section5.PublishedSection3Concrete.provedGinibreInput h

#check @CircularLawSections56.Section5.PublishedSection3Concrete.indicator_complex_full_of_published_literature
#check @CircularLawSections56.Section5.PublishedSection3Concrete.indicator_real_full_of_published_literature
#print CircularLawSections56.Section5.Section3TaperNonGaussianInputs
#check @CircularLawSections56.Section5.tapered_short_ring_of_section3_estimates_withoutBC12
