import CircularLawSection4
import CircularLawSection4.PaperPressureAssumptionFree

open CircularLawSection4

#print axioms CircularLawSection4.compound_mul
#print axioms CircularLawSection4.clearedRowCompanionCompound_eq_affine
#print axioms CircularLawSection4.cleared_floquet_exterior_identity
#print axioms CircularLawSection4.periodic_determinant_identity
#print axioms CircularLawSection4.physicalElimination_det
#print axioms CircularLawSection4.cyclicStateCopyRelabel_castSucc
#print axioms CircularLawSection4.cyclicStateCopyRelabel_last
#print axioms CircularLawSection4.stateIdentificationMatrix_row_eq_single_sub_single
#print axioms CircularLawSection4.cyclicCompanionStateMatrix_castSucc_row
#print axioms CircularLawSection4.differenceAnchorMatrix_det
#print axioms CircularLawSection4.stateIdentification_mul_right
#print axioms CircularLawSection4.differenceAnchor_mulVec_bijective
#print axioms CircularLawSection4.differenceAnchorMatrix_mulVec_stateCopyAnchorLift
#print axioms CircularLawSection4.differenceAnchorRight_anchorColumn
#print axioms CircularLawSection4.stateCopyPhysicalBlock_eq_sum_copies
#print axioms CircularLawSection4.cyclicCompanionPhysicalBlock_eq_sum_lastRow_copies
#print axioms CircularLawSection4.stateCopyPhysical_reduction
#print axioms CircularLawSection4.orderedStateCopyPhysicalCertificate
#print axioms CircularLawSection4.cyclicStateReindexSign_spec
#print axioms CircularLawSection4.orderedCyclicCompanionState_det
#print axioms CircularLawSection4.stateCopyAnchorRowScaling_det
#print axioms CircularLawSection4.stateCopyAnchorRowScaling_preserves_identification
#print axioms CircularLawSection4.stateCopyPhysicalBlock_anchorRowScaling
#print axioms CircularLawSection4.scaledOrderedStateCopyPhysicalCertificate
#print axioms CircularLawSection4.stateCopyPhysicalBlock_anchorRowScaling_det
#print axioms CircularLawSection4.scaledCyclicCompanionPhysicalCertificate
#print axioms CircularLawSection4.stateCopyPhysicalBlock_orderedCyclicCompanionState
#print axioms CircularLawSection4.scaledCyclicCompanionPhysicalBlock_eq
#print axioms CircularLawSection4.scaledPaperCyclicCompanionPhysicalBlock_eq
#print axioms CircularLawSection4.paperCyclicRawBandMatrix_reindex
#print axioms CircularLawSection4.paperCyclicBandReindexSign_spec
#print axioms CircularLawSection4.paperCyclicPhysicalMatrix_det
#print axioms CircularLawSection4.exists_sign_paperCyclicPhysicalMatrix_det
#print axioms CircularLawSection4.scaledCyclicCompanionPhysicalBlock_det
#print axioms CircularLawSection4.exists_sign_scaledCyclicCompanionPhysicalBlock_det
#print axioms CircularLawSection4.paperPeriodicDeterminantSign_spec
#print axioms CircularLawSection4.paperCyclicRawBandMatrix_det
#print axioms CircularLawSection4.exists_sign_paperCyclicRawBandMatrix_det
#print axioms CircularLawSection4.paperCyclicRawBandMatrix_eq_X_sub_zI
#print axioms CircularLawSection4.cyclicCompanionStateMatrix_eq_rawCyclicTransferSystem
#print axioms CircularLawSection4.finShiftedCyclicSystem_det
#print axioms CircularLawSection4.rawCyclicTransferSystem_det
#print axioms CircularLawSection4.paperCyclicCompanionState_det_eq_monodromy
#print axioms CircularLawSection4.paperCyclicRawBandMatrix_det_eq_monodromy
#print axioms CircularLawSection4.paperShiftedScalarBandMatrix_det_eq_clearedSignedCompoundTrace
#print axioms CircularLawSection4.paperXSubZI_det_eq_clearedSignedCompoundTrace
#print axioms CircularLawSection4.periodic_determinant_identity_of_matrix_cert
#print axioms CircularLawSection4.unitPivotCyclicEliminationCertificate
#print axioms CircularLawSection4.twoStepPeriodic_det
#print axioms CircularLawSection4.arbitraryLengthPeriodicEliminationCertificate
#print axioms CircularLawSection4.recursivePeriodicSystem_det
#print axioms CircularLawSection4.ResetWord.exists_singleton_domain_word
#print axioms CircularLawSection4.ResetWord.singletonWord_kills_other_degree
#print axioms CircularLawSection4.booleanSupport_singletonCertificate
#print axioms CircularLawSection4.ResetWord.arbitrary_singleton_domain_word
#print axioms CircularLawSection4.booleanSupport_arbitrarySingletonCertificate
#print axioms CircularLawSection4.finLeftShift_isTotallyUnimodular
#print axioms CircularLawSection4.finLeftShift_updateLast_isTotallyUnimodular
#print axioms CircularLawSection4.norm_orderedCoefficient_eq_one_of_ne_zero
#print axioms CircularLawSection4.singletonWordCertificate_of_word_norm_eq
#print axioms CircularLawSection4.rowFreeCompound_finLeftShift_ne_zero_iff_step_star
#print axioms CircularLawSection4.orderedCoefficient_star_ne_zero_iff_booleanSupportK
#print axioms CircularLawSection4.step_reset_exteriorState_iff
#print axioms CircularLawSection4.rowMinorCoefficient_finLeftShift_ne_zero_imp_step_reset
#print axioms CircularLawSection4.rowMinorCoefficient_finLeftShift_ne_zero_of_step_reset
#print axioms CircularLawSection4.rowMinorCoefficient_finLeftShift_ne_zero_iff_step_reset
#print axioms CircularLawSection4.orderedCoefficient_ne_zero_iff_exteriorSupportStep
#print axioms CircularLawSection4.orderedCoefficient_ne_zero_iff_booleanSupportK
#print axioms CircularLawSection4.orderedCoefficient_arbitrarySingletonCertificate
#print axioms CircularLawSection4.l2_opNorm_le_one_of_row_col_sparse_of_entry_norm_le_one
#print axioms CircularLawSection4.orderedCoefficient_ne_zero_imp_step
#print axioms CircularLawSection4.orderedCoefficient_l2_opNorm_le_one
#print axioms CircularLawSection4.clearedRowCompanionCompound_eq_orderedCoefficient
#print axioms CircularLawSection4.orderedRowLinearity_with_l2_contraction
#print axioms CircularLawSection4.chronologicalProduct_map_norm_eq_partialMapMatrix
#print axioms CircularLawSection4.wordOperator_norm_eq_booleanSupportK_of_step_data
#print axioms CircularLawSection4.singletonWordCertificate_of_step_data
#print axioms CircularLawSection4.fullMonomialCoefficient_booleanSupport_arbitrary_eq
#print axioms CircularLawSection4.isolated_booleanSupport_arbitrary_lower_bound
#print axioms CircularLawSection4.exists_entry_eq_exteriorFamilyMaxEntryNorm
#print axioms CircularLawSection4.exists_isolated_booleanSupport_maxEntry_lower_bound
#print axioms CircularLawSection4.exists_entry_ge_exteriorFamilyMaxL2OpNorm_div_card
#print axioms CircularLawSection4.exists_isolated_booleanSupport_maxL2OpNorm_lower_bound
#print axioms CircularLawSection4.norm_fullMonomialCoefficient_orderedCoefficient_arbitrary_eq
#print axioms CircularLawSection4.isolated_orderedCoefficient_arbitrary_lower_bound
#print axioms CircularLawSection4.exists_isolated_orderedCoefficient_maxEntry_lower_bound
#print axioms CircularLawSection4.exists_isolated_orderedCoefficient_maxL2OpNorm_lower_bound
#print axioms CircularLawSection4.exists_unit_coordinate_product_ge_card_sq_inv
#print axioms CircularLawSection4.exists_matrixEntry_mul_unitCoordinate_ge_opNorm_div_card_cube
#print axioms CircularLawSection4.exists_projective_singleton_coefficient_ge_of_norming_sum
#print axioms CircularLawSection4.exists_large_projective_singleton_coefficient
#print axioms CircularLawSection4.fullMonomialCoefficient_booleanSupport_eq
#print axioms CircularLawSection4.isolated_booleanSupport_diagonal_lower_bound
#print axioms CircularLawSection4.fullMonomialCoefficient_eq_of_singleton
#print axioms CircularLawSection4.isolated_full_monomial_lower_bound
#print axioms CircularLawSection4.closedSmallBall_topCoeff_le
#print axioms CircularLawSection4.MultiAffine.eval_translate
#print axioms CircularLawSection4.MultiAffine.topCoeff_translate
#print axioms CircularLawSection4.iid_real_multiaffine_bound_withDensity
#print axioms CircularLawSection4.iid_complex_multiaffine_bound_withDensity
#print axioms CircularLawSection4.integrable_truncatedLogLoss_of_power_smallBall
#print axioms CircularLawSection4.iid_real_truncatedLogLoss_withDensity
#print axioms CircularLawSection4.iid_complex_truncatedLogLoss_withDensity
#print axioms CircularLawSection4.measure_zeroSet_eq_zero_of_power_smallBall
#print axioms CircularLawSection4.tendsto_lintegral_truncatedLogLoss_nat
#print axioms CircularLawSection4.iid_real_positiveLogLoss_withDensity
#print axioms CircularLawSection4.iid_complex_positiveLogLoss_withDensity
#print axioms CircularLawSection4.directional_joint_smallBall_le
#print axioms CircularLawSection4.directional_joint_positiveLogLoss
#print axioms CircularLawSection4.iid_real_positiveLogLoss_of_intervalBound
#print axioms CircularLawSection4.freshClosure_L1_of_isolatedCoefficient
#print axioms CircularLawSection4.freshClosure_L1_of_powerSmallBall_and_excess
#print axioms CircularLawSection4.log_scale_sub_log_coefficient_le_of_power_lower_bound
#print axioms CircularLawSection4.memLp_two_and_integral_sq_le_of_unit_exponential_tail
#print axioms CircularLawSection4.memLp_two_and_integral_sq_le_of_exponential_tail
#print axioms CircularLawSection4.memLp_two_and_integral_sq_abs_log_sub_log_of_two_tails
#print axioms CircularLawSection4.memLp_two_and_integral_sq_abs_log_sub_log_of_parts
#print axioms CircularLawSection4.positiveLogSquare_le_scaledSquare
#print axioms CircularLawSection4.integrable_normalized_sum_sq_and_integral_le_one
#print axioms CircularLawSection4.integrable_and_integral_positiveLogSquare_le_of_scaledSecondMoment
#print axioms CircularLawSection4.exists_large_scalarized_slope
#print axioms CircularLawSection4.operatorAffine_norm_le_scale_mul_sum
#print axioms CircularLawSection4.real_operatorAffine_oneCoordinate_smallBall
#print axioms CircularLawSection4.complex_operatorAffine_oneCoordinate_smallBall
#print axioms CircularLawSection4.pressureDegrees_max_le
#print axioms CircularLawSection4.pressure_maximal_concentration_of_variance
#print axioms CircularLawSection4.uniformVariance_le_half_sum_resampling
#print axioms CircularLawSection4.variance_uniformCubeMeasure_le_half_card_mul_of_resampling_le
#print axioms CircularLawSection4.pressure_maximal_concentration_uniform_resampling
#print axioms CircularLawSection4.uniformResamplingEnergy_eq_replace_average
#print axioms CircularLawSection4.uniformVariance_le_half_card_mul_of_replace_sq_le
#print axioms CircularLawSection4.pressure_maximal_concentration_uniform_replace_sq
#print axioms CircularLawSection4.pmfResamplingEnergy_eq_replace_integral
#print axioms CircularLawSection4.pmfCubeVariance_le_half_sum_resampling
#print axioms CircularLawSection4.pressure_maximal_concentration_pmf_resampling
#print axioms CircularLawSection4.variance_prod_decomposition_bounded
#print axioms CircularLawSection4.variance_iidMeasure_one_eq_half_resampling_bounded
#print axioms CircularLawSection4.variance_iidMeasure_succ_decomposition_resampling_bounded
#print axioms CircularLawSection4.variance_iidMeasure_le_half_recursiveResamplingBudget_bounded
#print axioms CircularLawSection4.pressure_maximal_concentration_iid_recursiveResamplingBudget
#print axioms CircularLawSection4.iidRawResamplingEnergy_iidLastAverage_le
#print axioms CircularLawSection4.iidRecursiveResamplingBudget_le_sum_raw
#print axioms CircularLawSection4.variance_iidMeasure_le_half_sum_raw
#print axioms CircularLawSection4.variance_iidMeasure_le_half_card_mul_of_raw_le
#print axioms CircularLawSection4.pressure_maximal_concentration_iid_raw
#print axioms CircularLawSection4.symmetricClip_lipschitz
#print axioms CircularLawSection4.tendsto_variance_symmetricClip_nat
#print axioms CircularLawSection4.iidRawResamplingEnergy_symmetricClip_le
#print axioms CircularLawSection4.variance_iidMeasure_le_half_sum_raw_memLp
#print axioms CircularLawSection4.pressure_maximal_concentration_iid_raw_memLp
#print axioms CircularLawSection4.iidRawResamplingEnergy_le_four_mul_of_center_sq_integral_le_of_integrable
#print axioms CircularLawSection4.pressure_maximal_concentration_iid_of_center_sq_integral_le_memLp
#print axioms CircularLawSection4.iidRawResamplingEnergy_le_four_mul_of_center_sq_integral_le
#print axioms CircularLawSection4.pressure_maximal_concentration_iid_of_center_sq_integral_le
#print axioms CircularLawSection4.uniformResamplingEnergy_le_four_mul_of_center_sq_average_le
#print axioms CircularLawSection4.pressure_maximal_concentration_uniform_of_center_sq_average_le
#print axioms CircularLawSection4.uniformAverage_sq_le_exponentialTailSecondMomentBound
#print axioms CircularLawSection4.pressure_maximal_concentration_uniform_of_exponential_replacement_tails
#print axioms CircularLawSection4.eval_paperIndicatorFreshPolynomial_flatSample
#print axioms CircularLawSection4.iidRawResamplingEnergy_le_four_mul_of_fiber_memLp
#print axioms CircularLawSection4.measurable_fin_insertNth_uncurry
#print axioms CircularLawSection4.iidRawResamplingOuter_integrable_of_fiber_memLp
#print axioms CircularLawSection4.iidRawResamplingEnergy_le_four_mul_of_fiber_memLp_auto
#print axioms CircularLawSection4.integrable_of_tendsto_of_nonneg_of_integral_le
#print axioms CircularLawSection4.memLp_two_of_variance_symmetricClip_le
#print axioms CircularLawSection4.memLp_two_of_iid_raw_replacement_integrable
#print axioms CircularLawSection4.complex_paperIndicator_operatorAffine_memLp_two_and_integral_sq
#print axioms CircularLawSection4.paper_real_iid_operatorAffine_absLog_L2
#print axioms CircularLawSection4.PaperIndicatorWeights.complex_paperIndicatorOpenPressure_fiber_memLp_two_and_integral_sq_all_scales
#print axioms CircularLawSection4.PaperIndicatorWeights.real_paperIndicatorOpenPressure_fiber_memLp_two_and_integral_sq_all_scales
#print axioms CircularLawSection4.PaperIndicatorWeights.complex_paperIndicatorOpenPressure_rawResamplingEnergy_le
#print axioms CircularLawSection4.PaperIndicatorWeights.real_paperIndicatorOpenPressure_rawResamplingEnergy_le
#print axioms CircularLawSection4.PaperIndicatorWeights.variance_complex_paperIndicatorOpenPressure_le
#print axioms CircularLawSection4.PaperIndicatorWeights.variance_real_paperIndicatorOpenPressure_le
#print axioms CircularLawSection4.PaperIndicatorWeights.integral_max_complex_paperIndicatorOpenPressure_le
#print axioms CircularLawSection4.PaperIndicatorWeights.integral_max_real_paperIndicatorOpenPressure_le
#print axioms CircularLawSection4.flatIIDRows_measurePreserving
#print axioms CircularLawSection4.paperIndicatorFlatRows_measurePreserving
#print axioms CircularLawSection4.paperIndicatorRealFlatRows_measurePreserving
#print axioms CircularLawSection4.PaperIndicatorWeights.variance_complex_paperIndicatorFlatOpenPressure_le
#print axioms CircularLawSection4.PaperIndicatorWeights.variance_real_paperIndicatorFlatOpenPressure_le
#print axioms CircularLawSection4.PaperIndicatorWeights.integral_max_complex_paperIndicatorFlatOpenPressure_le
#print axioms CircularLawSection4.PaperIndicatorWeights.integral_max_real_paperIndicatorFlatOpenPressure_le
#print axioms CircularLawSection4.PaperIndicatorWeights.complex_paperIndicatorOpenPressure_rawOuter_integrable
#print axioms CircularLawSection4.PaperIndicatorWeights.real_paperIndicatorOpenPressure_rawOuter_integrable
#print axioms CircularLawSection4.PaperIndicatorWeights.complex_paperIndicatorOpenPressure_rawResamplingEnergy_le_auto
#print axioms CircularLawSection4.PaperIndicatorWeights.real_paperIndicatorOpenPressure_rawResamplingEnergy_le_auto
#print axioms CircularLawSection4.PaperIndicatorWeights.complex_paperIndicatorOpenPressure_memLp_two
#print axioms CircularLawSection4.PaperIndicatorWeights.real_paperIndicatorOpenPressure_memLp_two
#print axioms CircularLawSection4.PaperIndicatorWeights.variance_complex_paperIndicatorOpenPressure_le_auto
#print axioms CircularLawSection4.PaperIndicatorWeights.variance_real_paperIndicatorOpenPressure_le_auto
#print axioms CircularLawSection4.PaperIndicatorWeights.integral_max_complex_paperIndicatorOpenPressure_le_auto
#print axioms CircularLawSection4.PaperIndicatorWeights.integral_max_real_paperIndicatorOpenPressure_le_auto
#print axioms CircularLawSection4.PaperIndicatorWeights.variance_complex_paperIndicatorFlatOpenPressure_le_auto
#print axioms CircularLawSection4.PaperIndicatorWeights.variance_real_paperIndicatorFlatOpenPressure_le_auto
#print axioms CircularLawSection4.PaperIndicatorWeights.integral_max_complex_paperIndicatorFlatOpenPressure_le_auto
#print axioms CircularLawSection4.PaperIndicatorWeights.integral_max_real_paperIndicatorFlatOpenPressure_le_auto

#check CircularLawSection4.clearedRowCompanionCompound_eq_affine
#check CircularLawSection4.exists_sign_periodic_determinant_identity
#check CircularLawSection4.periodic_determinant_identity_of_matrix_cert
#check CircularLawSection4.cyclicStateCopyRelabel
#check CircularLawSection4.stateIdentificationMatrix_row_eq_single_sub_single
#check CircularLawSection4.cyclicCompanionStateMatrix_castSucc_row
#check CircularLawSection4.differenceAnchorMatrix
#check CircularLawSection4.differenceAnchorRight
#check CircularLawSection4.stateCopyAnchorLift
#check CircularLawSection4.differenceAnchorRight_anchorColumn
#check CircularLawSection4.stateCopyPhysicalBlock
#check CircularLawSection4.stateCopyPhysicalBlock_eq_dotProduct
#check CircularLawSection4.stateCopyPhysicalBlock_eq_sum_copies
#check CircularLawSection4.cyclicCompanionPhysicalBlock_eq_sum_lastRow_copies
#check CircularLawSection4.orderedStateCopyPhysicalCertificate
#check CircularLawSection4.cyclicStateReindexSign
#check CircularLawSection4.cyclicStateReindexSign_spec
#check CircularLawSection4.orderedCyclicCompanionState_det
#check CircularLawSection4.stateCopyAnchorRowScaling
#check CircularLawSection4.stateCopyAnchorRowScaling_det
#check CircularLawSection4.stateCopyAnchorRowScaling_preserves_identification
#check CircularLawSection4.stateCopyPhysicalBlock_anchorRowScaling
#check CircularLawSection4.scaledOrderedStateCopyPhysicalCertificate
#check CircularLawSection4.stateCopyPhysicalBlock_anchorRowScaling_det
#check CircularLawSection4.scaledCyclicCompanionPhysicalCertificate
#check CircularLawSection4.cyclicCompanionPhysicalMatrix
#check CircularLawSection4.stateCopyPhysicalBlock_orderedCyclicCompanionState
#check CircularLawSection4.scaledCyclicCompanionPhysicalBlock_apply
#check CircularLawSection4.scaledCyclicCompanionPhysicalBlock_eq
#check CircularLawSection4.paperSparseCyclicLastRow
#check CircularLawSection4.paperCyclicOrderedScaling
#check CircularLawSection4.paperCyclicPhysicalMatrix
#check CircularLawSection4.scaledPaperCyclicCompanionPhysicalBlock_apply
#check CircularLawSection4.scaledPaperCyclicCompanionPhysicalBlock_eq
#check CircularLawSection4.paperCyclicRawBandMatrix
#check CircularLawSection4.paperCyclicBandRowEquiv
#check CircularLawSection4.paperCyclicBandColumnEquiv
#check CircularLawSection4.paperCyclicRawBandMatrix_reindex
#check CircularLawSection4.paperCyclicBandReindexSign
#check CircularLawSection4.paperCyclicBandReindexSign_spec
#check CircularLawSection4.paperCyclicPhysicalMatrix_det
#check CircularLawSection4.exists_sign_paperCyclicPhysicalMatrix_det
#check CircularLawSection4.scaledCyclicCompanionPhysicalBlock_det
#check CircularLawSection4.exists_sign_scaledCyclicCompanionPhysicalBlock_det
#check CircularLawSection4.paperPeriodicDeterminantSign
#check CircularLawSection4.paperPeriodicDeterminantSign_spec
#check CircularLawSection4.paperCyclicRawBandMatrix_det
#check CircularLawSection4.exists_sign_paperCyclicRawBandMatrix_det
#check CircularLawSection4.paperCyclicRawBandMatrix_eq_X_sub_zI
#check CircularLawSection4.cyclicCompanionStateMatrix_eq_rawCyclicTransferSystem
#check CircularLawSection4.finShiftedCyclicSystem_det
#check CircularLawSection4.rawCyclicTransferSystem_det
#check CircularLawSection4.paperCyclicCompanionState_det_eq_monodromy
#check CircularLawSection4.paperCyclicRawBandMatrix_det_eq_monodromy
#check CircularLawSection4.paperShiftedScalarBandMatrix_det_eq_clearedSignedCompoundTrace
#check CircularLawSection4.paperXSubZI_det_eq_clearedSignedCompoundTrace
#check CircularLawSection4.unitPivotCyclicEliminationCertificate
#check CircularLawSection4.arbitraryLengthPeriodicEliminationCertificate
#check CircularLawSection4.recursivePeriodicSystem_det
#check CircularLawSection4.ResetWord.exists_singleton_domain_word
#check CircularLawSection4.booleanSupport_singletonCertificate
#check CircularLawSection4.booleanSupport_arbitrarySingletonCertificate
#check CircularLawSection4.orderedCoefficient
#check CircularLawSection4.norm_orderedCoefficient_eq_one_of_ne_zero
#check CircularLawSection4.singletonWordCertificate_of_word_norm_eq
#check CircularLawSection4.rowFreeCompound_finLeftShift_ne_zero_iff_step_star
#check CircularLawSection4.orderedCoefficient_star_ne_zero_iff_booleanSupportK
#check CircularLawSection4.step_reset_exteriorState_iff
#check CircularLawSection4.rowMinorCoefficient_finLeftShift_ne_zero_imp_step_reset
#check CircularLawSection4.rowMinorCoefficient_finLeftShift_ne_zero_of_step_reset
#check CircularLawSection4.rowMinorCoefficient_finLeftShift_ne_zero_iff_step_reset
#check CircularLawSection4.orderedCoefficient_ne_zero_iff_exteriorSupportStep
#check CircularLawSection4.orderedCoefficient_ne_zero_iff_booleanSupportK
#check CircularLawSection4.orderedCoefficient_arbitrarySingletonCertificate
#check CircularLawSection4.l2_opNorm_le_one_of_row_col_sparse_of_entry_norm_le_one
#check CircularLawSection4.orderedCoefficient_ne_zero_imp_step
#check CircularLawSection4.orderedCoefficient_l2_opNorm_le_one
#check CircularLawSection4.clearedRowCompanionCompound_eq_orderedCoefficient
#check CircularLawSection4.orderedRowLinearity_with_l2_contraction
#check CircularLawSection4.chronologicalProduct_map_norm_eq_partialMapMatrix
#check CircularLawSection4.singletonWordCertificate_of_step_data
#check CircularLawSection4.isolated_booleanSupport_arbitrary_lower_bound
#check CircularLawSection4.exists_entry_eq_exteriorFamilyMaxEntryNorm
#check CircularLawSection4.exists_isolated_booleanSupport_maxEntry_lower_bound
#check CircularLawSection4.exists_entry_ge_exteriorFamilyMaxL2OpNorm_div_card
#check CircularLawSection4.exists_isolated_booleanSupport_maxL2OpNorm_lower_bound
#check CircularLawSection4.norm_fullMonomialCoefficient_orderedCoefficient_arbitrary_eq
#check CircularLawSection4.isolated_orderedCoefficient_arbitrary_lower_bound
#check CircularLawSection4.exists_isolated_orderedCoefficient_maxEntry_lower_bound
#check CircularLawSection4.exists_isolated_orderedCoefficient_maxL2OpNorm_lower_bound
#check CircularLawSection4.exists_unit_coordinate_product_ge_card_sq_inv
#check CircularLawSection4.exists_matrixEntry_mul_unitCoordinate_ge_opNorm_div_card_cube
#check CircularLawSection4.exists_projective_singleton_coefficient_ge_of_norming_sum
#check CircularLawSection4.exists_large_projective_singleton_coefficient
#check CircularLawSection4.isolated_booleanSupport_diagonal_lower_bound
#check CircularLawSection4.isolated_full_monomial_lower_bound
#check CircularLawSection4.closedSmallBall_topCoeff_le
#check CircularLawSection4.MultiAffine.eval_translate
#check CircularLawSection4.MultiAffine.topCoeff_translate
#check CircularLawSection4.iid_real_multiaffine_bound_withDensity
#check CircularLawSection4.iid_complex_multiaffine_bound_withDensity
#check CircularLawSection4.iid_real_truncatedLogLoss_withDensity
#check CircularLawSection4.iid_complex_truncatedLogLoss_withDensity
#check CircularLawSection4.iid_real_positiveLogLoss_withDensity
#check CircularLawSection4.iid_complex_positiveLogLoss_withDensity
#check CircularLawSection4.directional_joint_smallBall_le
#check CircularLawSection4.directional_joint_positiveLogLoss
#check CircularLawSection4.iid_real_positiveLogLoss_of_intervalBound
#check CircularLawSection4.freshClosure_L1_of_isolatedCoefficient
#check CircularLawSection4.freshClosure_L1_of_powerSmallBall_and_excess
#check CircularLawSection4.log_scale_sub_log_coefficient_le_of_power_lower_bound
#check CircularLawSection4.memLp_two_and_integral_sq_le_of_exponential_tail
#check CircularLawSection4.memLp_two_and_integral_sq_abs_log_sub_log_of_two_tails
#check CircularLawSection4.memLp_two_and_integral_sq_abs_log_sub_log_of_parts
#check CircularLawSection4.positiveLogSquare_le_scaledSquare
#check CircularLawSection4.integrable_normalized_sum_sq_and_integral_le_one
#check CircularLawSection4.integrable_and_integral_positiveLogSquare_le_of_scaledSecondMoment
#check CircularLawSection4.exists_large_scalarized_slope
#check CircularLawSection4.real_operatorAffine_oneCoordinate_smallBall
#check CircularLawSection4.complex_operatorAffine_oneCoordinate_smallBall
#check CircularLawSection4.PaperIndicatorWeights.paperIndicatorOpenPressure
#check CircularLawSection4.PaperIndicatorWeights.complex_paperIndicatorOpenPressure_fiber_memLp_two_and_integral_sq_all_scales
#check CircularLawSection4.PaperIndicatorWeights.real_paperIndicatorOpenPressure_fiber_memLp_two_and_integral_sq_all_scales
#check CircularLawSection4.PaperIndicatorWeights.variance_complex_paperIndicatorOpenPressure_le
#check CircularLawSection4.PaperIndicatorWeights.variance_real_paperIndicatorOpenPressure_le
#check CircularLawSection4.PaperIndicatorWeights.integral_max_complex_paperIndicatorOpenPressure_le
#check CircularLawSection4.PaperIndicatorWeights.integral_max_real_paperIndicatorOpenPressure_le
#check CircularLawSection4.flatIIDRowsMeasurableEquiv
#check CircularLawSection4.flatIIDRows_measurePreserving
#check CircularLawSection4.paperIndicatorFlatRowsEquiv_apply_eq_Xi
#check CircularLawSection4.paperIndicatorRealFlatRowsEquiv_apply_eq_XiOfReal
#check CircularLawSection4.PaperIndicatorWeights.variance_complex_paperIndicatorFlatOpenPressure_le
#check CircularLawSection4.PaperIndicatorWeights.variance_real_paperIndicatorFlatOpenPressure_le
#check CircularLawSection4.PaperIndicatorWeights.integral_max_complex_paperIndicatorFlatOpenPressure_le
#check CircularLawSection4.PaperIndicatorWeights.integral_max_real_paperIndicatorFlatOpenPressure_le
#check CircularLawSection4.measurable_fin_insertNth_uncurry
#check CircularLawSection4.iidRawResamplingOuter_integrable_of_fiber_memLp
#check CircularLawSection4.iidRawResamplingEnergy_le_four_mul_of_fiber_memLp_auto
#check CircularLawSection4.integrable_of_tendsto_of_nonneg_of_integral_le
#check CircularLawSection4.memLp_two_of_variance_symmetricClip_le
#check CircularLawSection4.memLp_two_of_iid_raw_replacement_integrable
#check CircularLawSection4.PaperIndicatorWeights.complex_paperIndicatorOpenPressure_rawOuter_integrable
#check CircularLawSection4.PaperIndicatorWeights.real_paperIndicatorOpenPressure_rawOuter_integrable
#check CircularLawSection4.PaperIndicatorWeights.complex_paperIndicatorOpenPressure_rawResamplingEnergy_le_auto
#check CircularLawSection4.PaperIndicatorWeights.real_paperIndicatorOpenPressure_rawResamplingEnergy_le_auto
#check CircularLawSection4.PaperIndicatorWeights.complex_paperIndicatorOpenPressure_memLp_two
#check CircularLawSection4.PaperIndicatorWeights.real_paperIndicatorOpenPressure_memLp_two
#check CircularLawSection4.PaperIndicatorWeights.variance_complex_paperIndicatorOpenPressure_le_auto
#check CircularLawSection4.PaperIndicatorWeights.variance_real_paperIndicatorOpenPressure_le_auto
#check CircularLawSection4.PaperIndicatorWeights.integral_max_complex_paperIndicatorOpenPressure_le_auto
#check CircularLawSection4.PaperIndicatorWeights.integral_max_real_paperIndicatorOpenPressure_le_auto
#check CircularLawSection4.PaperIndicatorWeights.variance_complex_paperIndicatorFlatOpenPressure_le_auto
#check CircularLawSection4.PaperIndicatorWeights.variance_real_paperIndicatorFlatOpenPressure_le_auto
#check CircularLawSection4.PaperIndicatorWeights.integral_max_complex_paperIndicatorFlatOpenPressure_le_auto
#check CircularLawSection4.PaperIndicatorWeights.integral_max_real_paperIndicatorFlatOpenPressure_le_auto
#check CircularLawSection4.pressureDegrees_max_le
#check CircularLawSection4.pressure_maximal_concentration_of_variance
#check CircularLawSection4.uniformVariance_le_half_sum_resampling
#check CircularLawSection4.pressure_maximal_concentration_uniform_resampling
#check CircularLawSection4.uniformCubeReplace
#check CircularLawSection4.uniformVariance_le_half_card_mul_of_replace_sq_le
#check CircularLawSection4.pressure_maximal_concentration_uniform_replace_sq
#check CircularLawSection4.pmfResamplingEnergy_eq_replace_integral
#check CircularLawSection4.pmfCubeVariance_le_half_sum_resampling
#check CircularLawSection4.pressure_maximal_concentration_pmf_resampling
#check CircularLawSection4.variance_prod_decomposition_bounded
#check CircularLawSection4.variance_iidMeasure_one_eq_half_resampling_bounded
#check CircularLawSection4.variance_iidMeasure_succ_decomposition_resampling_bounded
#check CircularLawSection4.variance_iidMeasure_le_half_recursiveResamplingBudget_bounded
#check CircularLawSection4.pressure_maximal_concentration_iid_recursiveResamplingBudget
#check CircularLawSection4.iidRawResamplingEnergy
#check CircularLawSection4.iidRawResamplingEnergy_iidLastAverage_le
#check CircularLawSection4.iidRecursiveResamplingBudget_le_sum_raw
#check CircularLawSection4.variance_iidMeasure_le_half_sum_raw
#check CircularLawSection4.variance_iidMeasure_le_half_card_mul_of_raw_le
#check CircularLawSection4.pressure_maximal_concentration_iid_raw
#check CircularLawSection4.symmetricClip
#check CircularLawSection4.tendsto_variance_symmetricClip_nat
#check CircularLawSection4.variance_iidMeasure_le_half_sum_raw_memLp
#check CircularLawSection4.pressure_maximal_concentration_iid_raw_memLp
#check CircularLawSection4.iidRawResamplingEnergy_le_four_mul_of_center_sq_integral_le_of_integrable
#check CircularLawSection4.pressure_maximal_concentration_iid_of_center_sq_integral_le_memLp
#check CircularLawSection4.iidRawResamplingEnergy_le_four_mul_of_center_sq_integral_le
#check CircularLawSection4.pressure_maximal_concentration_iid_of_center_sq_integral_le
#check CircularLawSection4.uniformResamplingEnergy_le_four_mul_of_center_sq_average_le
#check CircularLawSection4.pressure_maximal_concentration_uniform_of_center_sq_average_le
#check CircularLawSection4.pressure_maximal_concentration_uniform_of_exponential_replacement_tails
