import CircularLawSection4.PaperPressureAssumptionFree

/-! Focused kernel-dependency audit for the flat random-matrix bridge. -/

#print axioms CircularLawSection4.flatIIDRows_measurePreserving
#print axioms CircularLawSection4.paperIndicatorFlatRows_measurePreserving
#print axioms CircularLawSection4.paperIndicatorRealFlatRows_measurePreserving
#print axioms CircularLawSection4.PaperIndicatorWeights.variance_complex_paperIndicatorFlatOpenPressure_le
#print axioms CircularLawSection4.PaperIndicatorWeights.variance_real_paperIndicatorFlatOpenPressure_le
#print axioms CircularLawSection4.PaperIndicatorWeights.integral_max_complex_paperIndicatorFlatOpenPressure_le
#print axioms CircularLawSection4.PaperIndicatorWeights.integral_max_real_paperIndicatorFlatOpenPressure_le
#print axioms CircularLawSection4.PaperIndicatorWeights.variance_complex_paperIndicatorFlatOpenPressure_le_auto
#print axioms CircularLawSection4.PaperIndicatorWeights.variance_real_paperIndicatorFlatOpenPressure_le_auto
#print axioms CircularLawSection4.PaperIndicatorWeights.integral_max_complex_paperIndicatorFlatOpenPressure_le_auto
#print axioms CircularLawSection4.PaperIndicatorWeights.integral_max_real_paperIndicatorFlatOpenPressure_le_auto
