import CircularLawSection4.PaperIsolatedFreshMonomial
import CircularLawSection4.PaperFreshClosureFull
import CircularLawSection4.FreshAtomProductSplit
import CircularLawSection4.PiRestrictMarginal
import CircularLawSection4.PaperFreshCoordinateMarginal
import CircularLawSection4.PaperProjectiveConditional
import CircularLawSection4.ProductIntegralUniformBound
import CircularLawSection4.LIntegralFiniteProduct
import CircularLawSection4.DirectionalKernelConstruction
import CircularLawSection4.DirectionalVectorLaw
import CircularLawSection4.DirectionalOperatorAffine
import CircularLawSection4.HeterogeneousProductSmallBall

/-!
# Axiom audit for the four final Section 4 closures

This file intentionally contains no proof.  It asks Lean to report the axiom
dependencies of the public theorems that close the four remaining manuscript
gaps: the literal `Z_B` isolated monomial, the one-fresh logarithmic closure,
projective observability/conditioning, and construction of the heterogeneous
directional conditional product.
-/

-- 1. The literal paper `Z_B` and its isolated full monomial.
#print axioms CircularLawSection4.PaperIndicatorWeights.eval_paperIndicatorFreshPolynomial_eq_freshZ
#print axioms CircularLawSection4.PaperIndicatorWeights.topCoeff_paperIndicatorFreshPolynomial_spectralShift
#print axioms CircularLawSection4.PaperIndicatorWeights.exists_paperIndicatorFreshZ_isolatedFullMonomial
#print axioms CircularLawSection4.PaperIndicatorWeights.exists_paperIndicatorFreshZ_isolatedFullMonomial_exp
#print axioms CircularLawSection4.PaperIndicatorWeights.exists_paperIndicatorFreshZ_isolatedFullMonomial_logScale
#print axioms CircularLawSection4.PaperIndicatorWeights.exists_paperIndicatorFlatSample_isolatedFullMonomial

-- 2. Generic one-fresh logarithmic closure and its finite-product integrals.
#print axioms CircularLawSection4.integrable_prod_and_integral_le_of_forall_integrable_integral_le
#print axioms CircularLawSection4.lintegral_fin_prod_eq_prod
#print axioms CircularLawSection4.freshClosure_L1_of_logParts
#print axioms CircularLawSection4.freshClosure_L1_of_isolatedCoefficient
#print axioms CircularLawSection4.freshClosure_L1_of_powerSmallBall_and_excess
#print axioms CircularLawSection4.splitFreshAtom_measurePreserving
#print axioms CircularLawSection4.measurePreserving_pi_restrict_injective
#print axioms CircularLawSection4.paperIndicatorFreshRowSite_injective
#print axioms CircularLawSection4.paperIndicatorFreshCoordinateIndex_injective
#print axioms CircularLawSection4.paperIndicatorFreshCoordinates_measurePreserving
#print axioms CircularLawSection4.paperIndicatorFreshAtoms_eq_coordinateRestriction
#print axioms CircularLawSection4.PaperIndicatorWeights.norm_paperIndicatorFreshZ_le
#print axioms CircularLawSection4.PaperIndicatorWeights.integrable_and_integral_paperIndicatorFreshZ_logExcess_le
#print axioms CircularLawSection4.PaperIndicatorWeights.complex_paperIndicatorFlatFreshZ_logExcess_le
#print axioms CircularLawSection4.PaperIndicatorWeights.real_paperIndicatorFlatFreshZ_logExcess_le
#print axioms CircularLawSection4.PaperIndicatorWeights.eval_paperIndicatorFreshPolynomial_eq_freshZ_replaceSelected
#print axioms CircularLawSection4.PaperIndicatorWeights.logDeficit_transport_of_measurePreserving
#print axioms CircularLawSection4.PaperIndicatorWeights.exists_complex_paperFreshAtomProduct_logDeficit_withDensity
#print axioms CircularLawSection4.PaperIndicatorWeights.exists_real_paperFreshAtomProduct_logDeficit_withDensity
#print axioms CircularLawSection4.PaperIndicatorWeights.paperIndicatorFreshAtomsOfReal_eq_coordinateRestriction
#print axioms CircularLawSection4.PaperIndicatorWeights.exists_complex_paperIndicatorFlatFreshZ_logDeficit_withDensity
#print axioms CircularLawSection4.PaperIndicatorWeights.exists_real_paperIndicatorFlatFreshZ_logDeficit_withDensity
#print axioms CircularLawSection4.PaperIndicatorWeights.complex_paperIndicatorFlatFreshZ_absLog_L1_withDensity
#print axioms CircularLawSection4.PaperIndicatorWeights.real_paperIndicatorFlatFreshZ_absLog_L1_withDensity

-- 3. Projective-coordinate observability and conditional expectation.
#print axioms CircularLawSection4.PaperIndicatorWeights.eval_paperProjectiveFreshPolynomial_eq_coordinate
#print axioms CircularLawSection4.PaperIndicatorWeights.norm_eval_paperProjectiveFreshPolynomial_replaced_le
#print axioms CircularLawSection4.PaperIndicatorWeights.log_norm_sub_log_topCoeff_le_paperProjectiveCoefficientLogLoss
#print axioms CircularLawSection4.logDeficit_le_of_coordinate_ae
#print axioms CircularLawSection4.integrable_logDeficit_of_coordinate
#print axioms CircularLawSection4.integrable_log_and_integral_log_ge_of_logDeficit
#print axioms CircularLawSection4.measure_zeroSet_of_coordinate
#print axioms CircularLawSection4.markovKernel_integral_log_ge_of_logDeficit
#print axioms CircularLawSection4.condExp_past_ae_eq_freshIntegral
#print axioms CircularLawSection4.condExp_past_ae_ge_of_freshIntegral_ge
#print axioms CircularLawSection4.PaperIndicatorWeights.exists_paperProjectiveFreshVector_complex_logDeficit_withDensity
#print axioms CircularLawSection4.PaperIndicatorWeights.exists_paperProjectiveFreshVector_real_logDeficit_of_intervalBound
#print axioms CircularLawSection4.PaperIndicatorWeights.exists_paperProjectiveFreshVector_directional_fiber_logDeficit
#print axioms CircularLawSection4.PaperIndicatorWeights.exists_paperProjectiveFreshVector_rawDirectional_fiber_logDeficit
#print axioms CircularLawSection4.PaperIndicatorWeights.exists_paperProjectiveFreshVector_directional_fiber_integral_log_ge
#print axioms CircularLawSection4.PaperIndicatorWeights.forall_past_exists_paperProjectiveFreshVector_directional_logDeficit
#print axioms CircularLawSection4.PaperIndicatorWeights.exists_paperProjectiveFreshVector_complex_integral_log_ge_withDensity
#print axioms CircularLawSection4.PaperIndicatorWeights.exists_paperProjectiveFreshVector_real_integral_log_ge_of_intervalBound

-- 4. The raw directional law and its heterogeneous conditional product.
#print axioms CircularLawSection4.exists_everywhereIntervalKernel
#print axioms CircularLawSection4.directionalAtom_map_pair_eq_compProd
#print axioms CircularLawSection4.directionalProductKernel_isMarkov
#print axioms CircularLawSection4.directionalProductKernel_apply_eq_pi
#print axioms CircularLawSection4.paperDirectionalProductModel_intervalBound
#print axioms CircularLawSection4.independentMeasure_prefixSmallBallConsistent
#print axioms CircularLawSection4.independent_realInput_complex_multiaffine_bound
#print axioms CircularLawSection4.independent_realInput_complex_positiveLogLoss
#print axioms CircularLawSection4.pi_realInput_complex_multiaffine_bound
#print axioms CircularLawSection4.pi_realInput_complex_positiveLogLoss
#print axioms CircularLawSection4.directionalProduct_fiber_smallBall_le
#print axioms CircularLawSection4.directionalProduct_fiber_positiveLogLoss
#print axioms CircularLawSection4.directionalProduct_joint_smallBall_le
#print axioms CircularLawSection4.directionalProduct_joint_positiveLogLoss
#print axioms CircularLawSection4.product_conditional_joint_law
#print axioms CircularLawSection4.DirectionalProductModel.condDistrib_snd_fst_ae_eq
#print axioms CircularLawSection4.iidAtom_map_directionalSplitVector_eq_compProd
#print axioms CircularLawSection4.reconstructedDirectionalOperatorAffine_eq_realInput
#print axioms CircularLawSection4.pi_realInputComplexOperatorAffine_smallBall_of_oneCoordinate
#print axioms CircularLawSection4.pi_realInputComplexOperatorAffine_arbitraryCoordinate_smallBall
#print axioms CircularLawSection4.directionalProduct_fiber_operatorAffine_smallBall
#print axioms CircularLawSection4.directionalProduct_fiber_operatorAffine_logDeficit_L2
#print axioms CircularLawSection4.directionalProduct_fiber_reconstructedOperatorAffine_logDeficit_L2
#print axioms CircularLawSection4.paperDirectional_fiber_operatorAffine_logDeficit_L2
#print axioms CircularLawSection4.paperDirectional_fiber_reconstructedOperatorAffine_logDeficit_L2
