import CircularLawSection4.OrderedRowLinearity
import CircularLawSection4.PaperPeriodicIdentityClosed
import CircularLawSection4.ArbitraryResetWord
import CircularLawSection4.PaperIsolatedFreshMonomial
import CircularLawSection4.Multiaffine
import CircularLawSection4.PaperCompanionInvertibility
import CircularLawSection4.DirectionalFreshClosure
import CircularLawSection4.DirectionalOperatorAffineFull
import CircularLawSection4.PaperPressureDirectionalL2
import CircularLawSection4.PaperPressureDirectionalConcentration
import CircularLawSection4.PaperPressureDirectionalAssumptionFree
import CircularLawSection4.PaperConditionalCompletion

/-!
# Axiom audit for the complete Section 4 proof chain

This file asks Lean to report the axiom dependencies of the final public
theorems added when closing the companion-invertibility, directional-density,
projective-positive-tail, past/fresh conditional-expectation, and pressure
concentration interfaces.  It intentionally contains no proof declarations.
-/

-- Representative endpoints for the manuscript's nine named results.
#print axioms CircularLawSection4.clearedRowCompanionCompound_eq_affine
#print axioms CircularLawSection4.paperXSubZI_det_eq_clearedSignedCompoundTrace
#print axioms CircularLawSection4.ResetWord.arbitrary_singleton_domain_word
#print axioms CircularLawSection4.PaperIndicatorWeights.exists_paperIndicatorFreshZ_isolatedFullMonomial
#print axioms CircularLawSection4.openSmallBall_topCoeff_le
#print axioms CircularLawSection4.PaperIndicatorWeights.complex_paperIndicatorFlatFreshZ_absLog_L1_withDensity
#print axioms CircularLawSection4.PaperIndicatorWeights.exists_paperProjectiveFreshVector_complex_integral_log_ge_withDensity_andSecondMoment
#print axioms CircularLawSection4.complex_paperIndicator_operatorAffine_absLog_L2_directional
#print axioms CircularLawSection4.PaperIndicatorWeights.integral_max_directional_paperIndicatorFlatOpenPressure_le_auto

-- Companion determinant, invertibility, and all exterior powers.
#print axioms CircularLawSection4.paperCyclicTransferMatrix_det
#print axioms CircularLawSection4.paperCyclicTransferMatrix_det_of_even
#print axioms CircularLawSection4.paperCyclicTransferMatrix_det_ne_zero
#print axioms CircularLawSection4.paperCyclicTransferMatrix_isUnit
#print axioms CircularLawSection4.compound_isUnit_of_isUnit_det
#print axioms CircularLawSection4.paperCyclicTransferMatrix_compound_isUnit
#print axioms CircularLawSection4.paperCyclicTransferMatrix_all_compounds_isUnit
#print axioms CircularLawSection4.paperCyclicTransferMatrix_clearedCompound_isUnit
#print axioms CircularLawSection4.paperShiftedScalarTransfer_det_of_even
#print axioms CircularLawSection4.paperShiftedScalarTransfer_det_eq_leftEdge_div_rightEdge
#print axioms CircularLawSection4.paperShiftedScalarTransfer_all_isUnit
#print axioms CircularLawSection4.rowCompanion_finLeftShift_det
#print axioms CircularLawSection4.rowCompanion_finLeftShift_det_of_even
#print axioms CircularLawSection4.rowCompanion_finLeftShift_isUnit
#print axioms CircularLawSection4.rowCompanion_finLeftShift_compound_isUnit
#print axioms CircularLawSection4.ae_paperIndicatorTransferMatrix_all_isUnit_complex_withDensity
#print axioms CircularLawSection4.ae_paperIndicatorTransferMatrix_all_isUnit_real_withDensity

-- Directional-density transport and the actual `Z_B` fresh closure.
#print axioms CircularLawSection4.reconstructedDirectionalAtom_parts
#print axioms CircularLawSection4.realInputEval_directionalSubstitute
#print axioms CircularLawSection4.norm_topCoeff_directionalSubstitute
#print axioms CircularLawSection4.directionalSubstitute_split_eval
#print axioms CircularLawSection4.iidAtom_directionalSplit_measurePreserving
#print axioms CircularLawSection4.iid_complex_positiveLogLoss_of_directionalDensity
#print axioms CircularLawSection4.PaperIndicatorWeights.exists_complex_paperFreshAtomProduct_logDeficit_withDirectionalDensity
#print axioms CircularLawSection4.PaperIndicatorWeights.exists_complex_paperIndicatorFlatFreshZ_logDeficit_withDirectionalDensity
#print axioms CircularLawSection4.PaperIndicatorWeights.complex_paperIndicatorFlatFreshZ_absLog_L1_withDirectionalDensity

-- Full two-sided directional operator-affine logarithm.
#print axioms CircularLawSection4.reconstructedDirectionalOperatorAffine_split_eq
#print axioms CircularLawSection4.norm_reconstructedDirectionalWeight_mul
#print axioms CircularLawSection4.directionalProduct_joint_reconstructedOperatorAffine_smallBall
#print axioms CircularLawSection4.iid_complex_operatorAffine_smallBall_of_directionalDensity
#print axioms CircularLawSection4.iid_complex_operatorAffine_logDeficit_L2_of_directionalDensity
#print axioms CircularLawSection4.complex_paperIndicator_operatorAffineFin_absLog_L2_directional
#print axioms CircularLawSection4.complex_paperIndicator_operatorAffine_absLog_L2_directional
#print axioms CircularLawSection4.PaperIndicatorWeights.directional_paperIndicatorOpenPressure_fiber_absLog_L2
#print axioms CircularLawSection4.PaperIndicatorWeights.directional_paperIndicatorOpenPressure_fiber_absLog_L2_all_scales

-- Directional row replacement, Efron--Stein, and literal flat pressure.
#print axioms CircularLawSection4.PaperIndicatorWeights.directional_paperIndicatorOpenPressure_replacement_sq_integrable
#print axioms CircularLawSection4.PaperIndicatorWeights.directional_paperIndicatorOpenPressure_rawResamplingEnergy_le
#print axioms CircularLawSection4.PaperIndicatorWeights.variance_directional_paperIndicatorOpenPressure_le
#print axioms CircularLawSection4.PaperIndicatorWeights.integral_max_directional_paperIndicatorOpenPressure_le
#print axioms CircularLawSection4.PaperIndicatorWeights.directional_paperIndicatorOpenPressure_rawOuter_integrable
#print axioms CircularLawSection4.PaperIndicatorWeights.directional_paperIndicatorOpenPressure_rawResamplingEnergy_le_auto
#print axioms CircularLawSection4.PaperIndicatorWeights.directional_paperIndicatorOpenPressure_memLp_two
#print axioms CircularLawSection4.PaperIndicatorWeights.variance_directional_paperIndicatorOpenPressure_le_auto
#print axioms CircularLawSection4.PaperIndicatorWeights.integral_max_directional_paperIndicatorOpenPressure_le_auto
#print axioms CircularLawSection4.PaperIndicatorWeights.variance_directional_paperIndicatorFlatOpenPressure_le_auto
#print axioms CircularLawSection4.PaperIndicatorWeights.integral_max_directional_paperIndicatorFlatOpenPressure_le_auto

-- Projective positive tail from the paper's second moment assumption.
#print axioms CircularLawSection4.PaperIndicatorWeights.norm_paperProjectiveFreshVector_le
#print axioms CircularLawSection4.PaperIndicatorWeights.integrable_and_integral_paperProjectiveFreshVector_logExcess_le
#print axioms CircularLawSection4.PaperIndicatorWeights.one_le_paperProjectiveFrozenAtomScale
#print axioms CircularLawSection4.PaperIndicatorWeights.norm_atom_le_paperProjectiveFrozenAtomScale
#print axioms CircularLawSection4.PaperIndicatorWeights.replacedFreshRowAtomSum_scaledSecondMoment
#print axioms CircularLawSection4.PaperIndicatorWeights.exists_paperProjectiveFreshVector_complex_integral_log_ge_withDensity_andSecondMoment
#print axioms CircularLawSection4.PaperIndicatorWeights.exists_paperProjectiveFreshVector_real_integral_log_ge_of_intervalBound_andSecondMoment

-- Actual past-dependent frozen family and canonical conditional expectation.
#print axioms CircularLawSection4.PaperIndicatorWeights.measurable_norm_paperIndicatorFreshZ_of_measurable_family
#print axioms CircularLawSection4.PaperIndicatorWeights.measurable_exteriorFamilyMaxL2OpNorm
#print axioms CircularLawSection4.condDistrib_snd_fst_prod_ae_eq_const
#print axioms CircularLawSection4.product_condExp_ae_eq_fiberIntegral_of_uniform_L1
#print axioms CircularLawSection4.PaperIndicatorWeights.paperFreshPositiveBound_nonneg
#print axioms CircularLawSection4.PaperIndicatorWeights.complex_paperIndicatorFlatFreshZ_joint_absLog_condExp_withDensity
#print axioms CircularLawSection4.PaperIndicatorWeights.real_paperIndicatorFlatFreshZ_joint_absLog_condExp_withDensity
