#!/usr/bin/env python3
"""Generate/check explicit Section 5/6 public-theorem axiom audit commands.

This deliberately supports the simple top-level declaration/scoping syntax
used by these projects, not arbitrary Lean syntax. Lean checks every generated
name and its transitive axiom set in CI. Private auxiliary declarations are
covered transitively when used, not counted as separate public theorems.
Print to stdout; this script never edits proof files or audit files.
"""

import argparse
from pathlib import Path
import re

from check_placeholders import code_only

ROOT = Path(__file__).resolve().parents[1]
NAME = r"[\w'.]+"
PROJECTS = {
    "section5": ("CircularLawSections56", ["CircularLawSections56"]),
    "section6": ("CircularLawSection6", ["CircularLawSection6",
                                          "CircularLawSection6.GinibreFiniteFormulaSources"]),
}


def public_theorems(source: str) -> list[str]:
    scopes: list[tuple[str, str]] = []
    names = []
    for line in code_only(source).splitlines():
        # These projects place namespace/section/declaration commands at column 0.
        match = re.fullmatch(rf"namespace\s+({NAME})\s*", line)
        if match:
            scopes.append(("namespace", match[1]))
            continue
        match = re.fullmatch(rf"(?:noncomputable\s+)?section(?:\s+({NAME}))?\s*", line)
        if match:
            scopes.append(("section", match[1] or ""))
            continue
        match = re.fullmatch(rf"end(?:\s+({NAME}))?\s*", line)
        if match:
            if not scopes:
                raise ValueError(f"Unmatched scope terminator: {line}")
            _, scope = scopes.pop()
            if match[1] and match[1] != scope:
                raise ValueError(f"Scope mismatch: {line}; expected {scope}")
            continue
        line = re.sub(r"^(?:@\[[^\]]*\]\s*)+", "", line)
        match = re.match(rf"(?:(private|protected)\s+)?(?:theorem|lemma)\s+({NAME})(?=\s|:|\{{|\(|$)", line)
        if match and match[1] != "private":
            name = match[2]
            prefix = ".".join(scope for kind, scope in scopes if kind == "namespace")
            names.append(name.removeprefix("_root_.") if name.startswith("_root_.")
                         else ".".join(filter(None, [prefix, name])))
        elif re.search(r"\b(theorem|lemma)\b", line) and not match:
            raise ValueError(f"Unsupported theorem declaration syntax: {line}")
    if any(kind == "namespace" or name for kind, name in scopes):
        raise ValueError(f"Unclosed named scopes: {scopes}")
    if len(names) != len(set(names)):
        raise ValueError("Duplicate public theorem name within one file")
    return names


def audit_text(project: str) -> str:
    directory, imports = PROJECTS[project]
    lines = [*(f"import {module}" for module in imports), "",
             "/-! Explicit public-theorem audit, generated by `scripts/public_theorem_audit.py`.",
             "Each command has the default checking limits. Ordinary hypotheses remain explicit.",
             "Private lemmas are checked transitively, not listed as public declarations. -/", ""]
    seen = set()
    source_root = ROOT / project / directory
    for path in sorted(source_root.rglob("*.lean")):
        names = public_theorems(path.read_text())
        if not names:
            continue
        if seen.intersection(names):
            raise ValueError(f"Duplicate public theorem names: {seen.intersection(names)}")
        seen.update(names)
        lines.append(f"-- {path.relative_to(source_root)}")
        lines.extend(f"#print axioms {name}" for name in names)
        lines.append("")
    if not seen:
        raise ValueError(f"No public {project} theorems found")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--project", choices=PROJECTS, required=True)
    args = parser.parse_args()
    expected = audit_text(args.project)
    if args.check:
        actual = (ROOT / args.project / "PublicTheoremAxiomAudit.lean").read_text()
        if actual != expected:
            raise SystemExit(f"Public {args.project} theorem audit is stale; regenerate and review it")
        print(f"{args.project} public audit coverage: {expected.count('#print axioms ')} theorems")
    else:
        print(expected, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
