import ShortRingAnchor

/-!
# Soundness audit

Compiling this module asks Lean to report the axioms used by the principal
source theorem and by each major internal bridge.  The expected output is
limited to mathlib's standard `propext`, `Classical.choice`, and
`Quot.sound`; in particular, none of the cited random-matrix interfaces is a
Lean axiom--each is an explicit parameter of the final theorem.
-/

#print axioms ShortRingAnchor.proposition36_of_source_scales
#print axioms ShortRingAnchor.verticalGrid_cover
#print axioms ShortRingAnchor.verticalStieltjesGridGood_norm_le_three
#print axioms ShortRingAnchor.smallHermitizationEigenvalueIndices_eq_v3
#print axioms ShortRingAnchor.verticalStieltjesGridGood_count
#print axioms ShortRingAnchor.verticalStieltjesGridGood_bad_le
#print axioms ShortRingAnchor.hardEdgeCutoff_eighth_power
#print axioms ShortRingAnchor.hardEdgeCutoff_lower
#print axioms ShortRingAnchor.eventually_formula311Error_hardEdge
#print axioms ShortRingAnchor.hermitizationAllCutoffsCountingInput_of_v3_model
#print axioms ShortRingAnchor.hermitizationAllCutoffsCountingInput_cyclic
#print axioms ShortRingAnchor.proposition36_cyclicShortRing_of_atom_copies_bbv_and_lsv
#print axioms ShortRingAnchor.proposition36_cyclicShortRing_of_source_scales
#print axioms ShortRingAnchor.proposition36_matrix_form_highProbability
#print axioms ShortRingAnchor.proposition36_matrix_form_ae
#print axioms ShortRingAnchor.empiricalLog_convergesInProbability_of_truncations
#print axioms ShortRingAnchor.abs_empiricalClippedLog_sub_le_cdfDistanceOn_zero_sq
#print axioms ShortRingAnchor.normalizedSmallLogMass_convergesInProbability_zero
#print axioms ShortRingAnchor.ginibreSmallLogMass_convergesInProbability_zero
#print axioms ShortRingAnchor.upperRawLogTail_le_log_div_sq_mul_sq
#print axioms ShortRingAnchor.sum_sq_matrixSingularValue_eq_sum_norm_sq_entries
#print axioms ShortRingAnchor.upperSecondMomentInputs_of_centered_matrix_entries
#print axioms ShortRingAnchor.centeredMatrixRowSecondMomentInputs_cyclicShortRing
#print axioms ShortRingAnchor.normalizedDenseMatrixProcess_centeredRowSecondMomentInputs
#print axioms ShortRingAnchor.AtomMomentAssumption21.integrable
#print axioms ShortRingAnchor.AtomMomentAssumption21.normSqIntegrable
#print axioms ShortRingAnchor.RingEntryMomentCopies21.centeredMatrixRowSecondMomentInputs
#print axioms ShortRingAnchor.DenseAtomMomentCopies21.centeredMatrixRowSecondMomentInputs
#print axioms ShortRingAnchor.theorem31LeastSingularValueInput_of_minimum
#print axioms ShortRingAnchor.Theorem31MinimumSingularValueInput.det_ne_zero_on_good
#print axioms ShortRingAnchor.Theorem31MinimumSingularValueInput.singular_probability_tendsto_zero
#print axioms ShortRingAnchor.UpperCorrectionsUniformlyNegligible.congr_on_good
#print axioms ShortRingAnchor.shiftedNonsingularInProbability_of_ae
#print axioms ShortRingAnchor.Proposition34AllCutoffsInput.specialize_eventually
#print axioms ShortRingAnchor.smallSingularValue_card_le_smallHermitizationEigenvalue_card
#print axioms ShortRingAnchor.proposition34AllCutoffsInput_of_hermitization
#print axioms ShortRingAnchor.sourceHardEdgeError_tendsto_zero
#print axioms ShortRingAnchor.sourceBulkCutoffBookkeeping_tendsto_zero
#print axioms ShortRingAnchor.manuscriptHardEdgeCutoff_le_sourceCutoff_eventually
#print axioms ShortRingAnchor.norm_det_eq_prod_matrixSingularValue
#print axioms ShortRingAnchor.shiftedDetPolynomial_ne_zero
#print axioms ShortRingAnchor.shifted_det_ne_zero_ae_of_law_absolutelyContinuous
#print axioms ShortRingAnchor.cyclicShortRingShiftedDetPolynomial_ne_zero
#print axioms ShortRingAnchor.cyclicShortRing_shifted_det_ne_zero_ae
#print axioms ShortRingAnchor.mvPolynomial_eval_ne_zero_ae_pi
#print axioms ShortRingAnchor.mvPolynomial_zeroSet_volume
#print axioms ShortRingAnchor.hasNullMvPolynomialZeroSets_pi
#print axioms ShortRingAnchor.hasNullMvPolynomialZeroSets_volume
#print axioms ShortRingAnchor.HasBoundedDensityWithRespectTo.absolutelyContinuous
#print axioms ShortRingAnchor.AtomDensityAlternative21.nullSingletonClass
#print axioms ShortRingAnchor.finite_product_absolutelyContinuous
#print axioms ShortRingAnchor.independent_jointLaw_absolutelyContinuous
#print axioms ShortRingAnchor.independent_complex_jointLaw_of_boundedDensity
#print axioms ShortRingAnchor.independent_real_jointLaw_of_boundedDensity
#print axioms ShortRingAnchor.shifted_det_ne_zero_ae_of_law_absolutelyContinuous_volume
#print axioms ShortRingAnchor.mvPolynomial_ne_zero_ae_of_independent_nonatomic
#print axioms ShortRingAnchor.mvPolynomial_ne_zero_ae_of_independent_density
#print axioms ShortRingAnchor.shifted_det_ne_zero_ae_of_independent_density
#print axioms ShortRingAnchor.cyclicShortRing_shifted_det_ne_zero_ae_of_independent_density
#print axioms ShortRingAnchor.det_div_sub_smul_ne_zero
#print axioms ShortRingAnchor.normalizedDense_shifted_det_ne_zero_ae_of_independent_density
#print axioms ShortRingAnchor.normalizedDense_shiftedNonsingularInProbability_of_independent_density

-- BC12 finite-formula route: the external formulas remain theorem
-- parameters.  This audit does not claim that those parameters are proved.
#print axioms ShortRingAnchor.BC12.ginibreOnePointDensity_le_inv_pi
#print axioms ShortRingAnchor.BC12.ginibreOnePointDensity_le_gaussian
#print axioms ShortRingAnchor.BC12.ginibreOnePointDensity_tendsto
#print axioms ShortRingAnchor.BC12.norm_ne_one_ae_complex
#print axioms ShortRingAnchor.BC12.integral_mul_ginibreOnePointDensity_tendsto
#print axioms ShortRingAnchor.BC12.centered_convergesInProbability_of_square_bound
#print axioms ShortRingAnchor.BC12.convergesInProbability_of_mean_and_square_bound
#print axioms ShortRingAnchor.BC12.negativeMomentTightness_of_uniform_integral_bound
#print axioms ShortRingAnchor.BC12.ginibre_variance_le_of_formulas
#print axioms ShortRingAnchor.BC12.ginibre_statistic_convergesInProbability_of_formulas
#print axioms ShortRingAnchor.BC12.integrable_log_sq_mul_ginibreEnvelope
#print axioms ShortRingAnchor.BC12.integrable_abs_log_mul_ginibreEnvelope
#print axioms ShortRingAnchor.BC12.integral_eq_radial_circleAverage
#print axioms ShortRingAnchor.BC12.integral_mul_log_from_zero
#print axioms ShortRingAnchor.BC12.integral_log_mul_circularDensity
#print axioms ShortRingAnchor.BC12.exists_eigenvalueEnumeration
#print axioms ShortRingAnchor.BC12.matrixEigenvalues_spec
#print axioms ShortRingAnchor.BC12.eigenvalues_ne_fixed_ae_of_firstMoment
#print axioms ShortRingAnchor.BC12.normalizedShiftLogDet_eq_eigenvalueStatistic
#print axioms ShortRingAnchor.BC12.ginibre_log_statistic_convergesInProbability_of_formulas
#print axioms ShortRingAnchor.BC12.ginibre_logdet_convergesInProbability_of_formulas
#print axioms ShortRingAnchor.BC12.ginibre_matrix_logdet_convergesInProbability_of_formulas

-- New short-route deductions. These audits do not assert that the actual
-- Gaussian/model adapters or the entire Lemma 3.5 endpoint are complete.
#print axioms ShortRingAnchor.BC12.continuousOn_rpow_positive_interval
#print axioms ShortRingAnchor.BC12.integral_lower_indicator_eq_clamp
#print axioms ShortRingAnchor.BC12.integral_negative_power_kernel
#print axioms ShortRingAnchor.BC12.clamped_negativePower_layerCake
#print axioms ShortRingAnchor.BC12.sum_lower_indicators
#print axioms ShortRingAnchor.BC12.empirical_clamped_negativePower_le
#print axioms ShortRingAnchor.BC12.negativePower_le_clamped_add_low
#print axioms ShortRingAnchor.BC12.normalizedNegativeMoment_le_of_count
#print axioms ShortRingAnchor.BC12.boundedInProbability_of_bound_on_good
#print axioms ShortRingAnchor.BC12.negativeMomentTightness_of_count_and_lower
#print axioms ShortRingAnchor.BC12.polynomial_negativeMoment_balance
#print axioms ShortRingAnchor.BC12.normalizedNegativeMoment_one_div_128_le
#print axioms ShortRingAnchor.horizontalGrid_cover
#print axioms ShortRingAnchor.horizontalGridSize_le
#print axioms ShortRingAnchor.horizontalGrid_comparison
#print axioms ShortRingAnchor.measure_horizontal_comparison_bad_le
#print axioms ShortRingAnchor.eventually_formula311Error_le_explicit_allEta
#print axioms ShortRingAnchor.eventually_formula311Error_le_explicit_nat_allEta
#print axioms ShortRingAnchor.horizontalGridSize_polynomial_le
#print axioms ShortRingAnchor.horizontalPolynomial_interpolation_error_le
#print axioms ShortRingAnchor.inverse_height_sq_le_dimension
#print axioms ShortRingAnchor.horizontalGrid_comparison_polynomial
#print axioms ShortRingAnchor.horizontalPolynomial_failure_budget
#print axioms ShortRingAnchor.measure_horizontal_comparison_bad_polynomial_le
#print axioms ShortRingAnchor.probability_tendsto_zero_of_truncated_and_tight
#print axioms ShortRingAnchor.probability_tendsto_zero_of_truncated_and_mean_bound

-- Lemma 3.5, complete finite-spectrum Poisson smoothing and squared-CDF conversion.
#print axioms ShortRingAnchor.arctan_le_self_nonneg
#print axioms ShortRingAnchor.arctan_upper_tail_le
#print axioms ShortRingAnchor.arctan_lower_tail_le
#print axioms ShortRingAnchor.poissonWindow_nonneg
#print axioms ShortRingAnchor.poissonWindow_le_one
#print axioms ShortRingAnchor.one_le_poissonWindow_enlarged_add_tail
#print axioms ShortRingAnchor.closedIntervalIndicator_le_poissonWindow_enlarged_add_tail
#print axioms ShortRingAnchor.poissonWindow_le_closedIntervalIndicator_enlarged_add_tail
#print axioms ShortRingAnchor.continuous_poissonKernel_shift
#print axioms ShortRingAnchor.hasDerivAt_arctan_shift
#print axioms ShortRingAnchor.poissonWindow_eq_integral
#print axioms ShortRingAnchor.smoothing_empiricalAverage_mono
#print axioms ShortRingAnchor.smoothing_empiricalAverage_add_const
#print axioms ShortRingAnchor.empiricalIntervalMass_le_smoothed_enlarged
#print axioms ShortRingAnchor.empiricalSmoothedMass_le_interval_enlarged
#print axioms ShortRingAnchor.continuous_empiricalStieltjes_im
#print axioms ShortRingAnchor.empiricalSmoothedMass_eq_integral_im
#print axioms ShortRingAnchor.empiricalSmoothedMass_le_length_mul
#print axioms ShortRingAnchor.empiricalSmoothedMass_le_comparison
#print axioms ShortRingAnchor.empiricalIntervalMass_enlarged_le
#print axioms ShortRingAnchor.empiricalIntervalMass_le_length_from_stieltjes
#print axioms ShortRingAnchor.empiricalIntervalMass_le_of_local_stieltjes
#print axioms ShortRingAnchor.abs_empiricalIntervalMass_sub_le_of_local_stieltjes
#print axioms ShortRingAnchor.compact_interval_comparison_of_stieltjes
#print axioms ShortRingAnchor.closedIntervalIndicator_sqrt_eq
#print axioms ShortRingAnchor.empiricalIntervalMass_symmetrized_sqrt
#print axioms ShortRingAnchor.squaredCdfDistanceOn_le_of_stieltjes
#print axioms ShortRingAnchor.empiricalIntervalMass_zero_eq_cdf
#print axioms ShortRingAnchor.isBigOInProbability_of_bound_on_good
#print axioms ShortRingAnchor.lemma35LocalBulkComparisonInput_of_stieltjes

-- Actual-matrix Hermitization and canonical v3 probability integration.
#print axioms ShortRingAnchor.hermitization_shift_eq_fromBlocks
#print axioms ShortRingAnchor.trace_eq_diagonalBlock_traces
#print axioms ShortRingAnchor.hermitization_inverse_block_equations
#print axioms ShortRingAnchor.hermitization_inverse_diagonal_traces_eq
#print axioms ShortRingAnchor.hermitization_inverse_lowerBlock_gram
#print axioms ShortRingAnchor.real_sub_upperHalfPlane_ne_zero
#print axioms ShortRingAnchor.real_sq_sub_upperHalfPlane_sq_ne_zero
#print axioms ShortRingAnchor.symmetric_resolvent_pair
#print axioms ShortRingAnchor.gram_shift_apply_rightSingularVector
#print axioms ShortRingAnchor.gram_solution_apply_rightSingularVector
#print axioms ShortRingAnchor.trace_gram_solution_eq_singular_sum
#print axioms ShortRingAnchor.normalizedTrace_hermitization_inverse_eq_singularStieltjes
#print axioms ShortRingAnchor.matrix_stieltjesTrace_eq_symmetric_singularValues
#print axioms ShortRingAnchor.matrix_squaredCdfDistanceOn_le_of_stieltjes
#print axioms ShortRingAnchor.v3_formula311_canonical_on_good
#print axioms ShortRingAnchor.v3_concentration_bad_le
#print axioms ShortRingAnchor.v3_pointwise_comparison_bad_le
#print axioms ShortRingAnchor.localBulkRateExponent_pos
#print axioms ShortRingAnchor.localBulkHeight_lower
#print axioms ShortRingAnchor.localBulkHeight_scale
#print axioms ShortRingAnchor.sqrt_localBulkHeight_le_rate
#print axioms ShortRingAnchor.eventually_formula311Error_localBulkHeight
#print axioms ShortRingAnchor.localBulk_rate_tendsto_zero
#print axioms ShortRingAnchor.measure_compactStieltjesGridGood_compl_le
#print axioms ShortRingAnchor.compactStieltjesGridGood_comparison
#print axioms ShortRingAnchor.compactStieltjesGridGood_reference_im_le_three
#print axioms ShortRingAnchor.matrix_stieltjesTrace_horizontal_lipschitz
#print axioms ShortRingAnchor.matrixLocalBulkGood_cdf_bound
#print axioms ShortRingAnchor.matrixLocalBulkGood_bad_le
#print axioms ShortRingAnchor.matrixLocalBulk_failure_budget_tendsto_zero
#print axioms ShortRingAnchor.lemma35LocalBulkComparisonInput_of_v3_models
#print axioms Arxiv2410V3.probabilityAtLeast_stieltjesTrace_complexConcentrationGood_v3_thirtytwo
#print axioms Arxiv2410V3.BVH.bvh_remark613_specialized_v3
#print axioms Arxiv2410V3.BVH.canonicalGaussianCompanion

-- Concrete cyclic/dense models and removal of the source-facing Lemma 3.5 premise.
#print axioms ShortRingAnchor.cyclicColumn_row_bijective
#print axioms ShortRingAnchor.cyclicPlacement_sum_at
#print axioms ShortRingAnchor.cyclicShortRingMatrix_at
#print axioms ShortRingAnchor.cyclicShortRingMatrix_off_band
#print axioms ShortRingAnchor.cyclicVarianceCoefficient
#print axioms ShortRingAnchor.cyclicVarianceCoefficient_at
#print axioms ShortRingAnchor.cyclicVarianceCoefficient_off_band
#print axioms ShortRingAnchor.cyclicVarianceCoefficient_sq
#print axioms ShortRingAnchor.cyclicVarianceCoefficient_col_sq_sum
#print axioms ShortRingAnchor.cyclicVarianceProfile
#print axioms ShortRingAnchor.cyclicVarianceProfile_isBandwidth
#print axioms ShortRingAnchor.iIndepFun_of_constant_outside
#print axioms ShortRingAnchor.AtomMomentAssumption21.of_identDistrib
#print axioms ShortRingAnchor.ringEntryMomentCopies21_of_independentAtomCopies
#print axioms ShortRingAnchor.denseAtomMomentCopies21_of_independentAtomCopies
#print axioms ShortRingAnchor.identDistrib_zero_probability
#print axioms ShortRingAnchor.cyclicShortRingRandomMatrix_entries_independent
#print axioms ShortRingAnchor.cyclicShortRingRandomMatrix_entry_law
#print axioms ShortRingAnchor.cyclicV3Model
#print axioms ShortRingAnchor.denseVarianceCoefficient_sq
#print axioms ShortRingAnchor.denseVarianceProfile
#print axioms ShortRingAnchor.denseVarianceProfile_isBandwidth
#print axioms ShortRingAnchor.denseV3Model
#print axioms ShortRingAnchor.eventually_cyclic_bandwidth_ge_half_power
#print axioms ShortRingAnchor.dense_bandwidth_ge_half_power
#print axioms ShortRingAnchor.localBulkRateExponent_half_eq
#print axioms ShortRingAnchor.sourceV3MomentBudget
#print axioms ShortRingAnchor.sourceV3MomentBudget_ge_eight
#print axioms ShortRingAnchor.sourceV3MomentBudget_ge_left
#print axioms ShortRingAnchor.sourceV3MomentBudget_ge_right
#print axioms ShortRingAnchor.AtomDensityAlternative21.of_identDistrib
#print axioms ShortRingAnchor.lemma35LocalBulkComparisonInput_cyclic_dense
#print axioms ShortRingAnchor.proposition36_cyclicShortRing_of_atom_copies_and_bbv
