import BernoulliSection9.ConditionalCook

/-!
# Conditional Cook on a square selected from a global iid family

The two terminal Cook squares are subsets of the seven-block packet family,
but their deformations also use packet coordinates outside the residual
submatrix.  Consequently the conditioning sigma-field must be generated by
the complement of the square in the *global* packet family, not merely by
the complement inside the residual restriction.

This file supplies that generic wrapper.  The square, its fresh sigma-field,
the full-coordinate complement, and their independence are all constructed
from one injective coordinate map.  No independence or measurability
certificate is exposed to a final Section 9 theorem.
-/

noncomputable section

namespace BernoulliSection9

open MeasureTheory ProbabilityTheory
open scoped Matrix.Norms.L2Operator

universe u v

/-- Sigma-field generated by a selected square in a global iid family. -/
@[instance_reducible] def IidSubgaussianFamily.coordinateSquareFreshSigma
    {Omega iota : Type*} [MeasurableSpace Omega]
    {mu : Measure Omega} [Fintype iota] [DecidableEq iota]
    {n : Nat} (X : IidSubgaussianFamily Omega mu iota)
    (label : (Fin n × Fin n) ↪ iota) : MeasurableSpace Omega :=
  X.coordinateSigma (selectedCoordinateSet label)

/-- Sigma-field generated by every global coordinate outside the square. -/
@[instance_reducible] def IidSubgaussianFamily.coordinateSquareConditioningSigma
    {Omega iota : Type*} [MeasurableSpace Omega]
    {mu : Measure Omega} [Fintype iota] [DecidableEq iota]
    {n : Nat} (X : IidSubgaussianFamily Omega mu iota)
    (label : (Fin n × Fin n) ↪ iota) : MeasurableSpace Omega :=
  X.coordinateSigma (Finset.univ \ selectedCoordinateSet label)

theorem IidSubgaussianFamily.coordinateSquareFreshSigma_le
    {Omega iota : Type*} [mOmega : MeasurableSpace Omega]
    {mu : Measure Omega} [Fintype iota] [DecidableEq iota]
    {n : Nat} (X : IidSubgaussianFamily Omega mu iota)
    (label : (Fin n × Fin n) ↪ iota) :
    X.coordinateSquareFreshSigma label ≤ mOmega :=
  X.coordinateSigma_le _

theorem IidSubgaussianFamily.coordinateSquareConditioningSigma_le
    {Omega iota : Type*} [mOmega : MeasurableSpace Omega]
    {mu : Measure Omega} [Fintype iota] [DecidableEq iota]
    {n : Nat} (X : IidSubgaussianFamily Omega mu iota)
    (label : (Fin n × Fin n) ↪ iota) :
    X.coordinateSquareConditioningSigma label ≤ mOmega :=
  X.coordinateSigma_le _

/-- The selected square is independent of every other coordinate of the
global iid family. -/
theorem IidSubgaussianFamily.coordinateSquareFresh_indep_conditioning
    {Omega iota : Type*} [mOmega : MeasurableSpace Omega]
    {mu : Measure Omega} [Fintype iota] [DecidableEq iota]
    {n : Nat} (X : IidSubgaussianFamily Omega mu iota)
    (label : (Fin n × Fin n) ↪ iota) :
    Indep (X.coordinateSquareFreshSigma label)
      (X.coordinateSquareConditioningSigma label) mu :=
  X.selectedSigma_indep_complement label

/-- Every atom of the selected concrete square is measurable in its fresh
sigma-field. -/
theorem IidSubgaussianFamily.coordinateSquare_atom_measurable
    {Omega iota : Type*} [mOmega : MeasurableSpace Omega]
    {mu : Measure Omega} [Fintype iota] [DecidableEq iota]
    {n : Nat} (X : IidSubgaussianFamily Omega mu iota)
    (label : (Fin n × Fin n) ↪ iota) (p : Fin n × Fin n) :
    @Measurable Omega Real (X.coordinateSquareFreshSigma label) _
      ((X.squareRestriction label).atom p) := by
  change @Measurable Omega Real
    (X.coordinateSigma (selectedCoordinateSet label)) _ (X.atom (label p))
  simpa [IidSubgaussianFamily.reindex] using
    X.reindexed_atom_measurable_selectedSigma label p

/-- Every global atom outside the selected square is measurable in the
square's full-coordinate complement sigma-field.  This is the entrywise
tool used to prove that the literal CUR deformation is conditionally
measurable. -/
theorem IidSubgaussianFamily.coordinateSquare_complement_atom_measurable
    {Omega iota : Type*} [mOmega : MeasurableSpace Omega]
    {mu : Measure Omega} [Fintype iota] [DecidableEq iota]
    {n : Nat} (X : IidSubgaussianFamily Omega mu iota)
    (label : (Fin n × Fin n) ↪ iota) (i : iota)
    (hi : i ∉ selectedCoordinateSet label) :
    @Measurable Omega Real (X.coordinateSquareConditioningSigma label) _
      (X.atom i) := by
  let i' : (Finset.univ \ selectedCoordinateSet label : Finset iota) :=
    ⟨i, by simp [hi]⟩
  simpa [IidSubgaussianFamily.coordinateSquareConditioningSigma] using
    X.atom_measurable_coordinateSigma
      (Finset.univ \ selectedCoordinateSet label) i'

/-- Strong-measurability form of
`coordinateSquare_complement_atom_measurable`. -/
theorem IidSubgaussianFamily.coordinateSquare_complement_atom_stronglyMeasurable
    {Omega iota : Type*} [mOmega : MeasurableSpace Omega]
    {mu : Measure Omega} [Fintype iota] [DecidableEq iota]
    {n : Nat} (X : IidSubgaussianFamily Omega mu iota)
    (label : (Fin n × Fin n) ↪ iota) (i : iota)
    (hi : i ∉ selectedCoordinateSet label) :
    @StronglyMeasurable Omega Real _
      (X.coordinateSquareConditioningSigma label) (X.atom i) :=
  (X.coordinateSquare_complement_atom_measurable label i hi).stronglyMeasurable

/-- Cook's conditional estimate specialized to an internally selected square
of a global iid family and conditioned on all remaining global coordinates.
Only the deformation's concrete measurability and norm estimate remain for
the CUR calculation to prove. -/
theorem CookDeformedSquareInput.coordinateSquare_conditional
    {Omega : Type u} [mOmega : MeasurableSpace Omega]
    (cook : CookDeformedSquareInput.{u, u}) (mu : Measure Omega)
    [IsProbabilityMeasure mu]
    {iota : Type v} [Fintype iota] [DecidableEq iota]
    (X : IidSubgaussianFamily Omega mu iota)
    {n : Nat} (label : (Fin n × Fin n) ↪ iota)
    (profile : CookProfile n) (L : Real)
    (D : Omega → Matrix (Fin n) (Fin n) Complex)
    (hsubgaussian : X.subgaussianParameter ≤ cook.subgaussianBound)
    (hprofile : ∀ i j,
      cook.lowerWeight ≤ profile.weight i j ∧
        profile.weight i j ≤ cook.upperWeight)
    (hn : 2 ≤ n) (hL : 0 ≤ L)
    (hDmeas : ∀ i j,
      @StronglyMeasurable Omega Complex _
        (X.coordinateSquareConditioningSigma label)
        (fun omega => D omega i j))
    (hDnorm : ∀ᵐ omega ∂mu, ‖D omega‖ ≤ (n : Real) ^ L) :
    MeasurableSet
        (cookBadEvent (X.squareRestriction label) profile D (cook.beta L)) ∧
      ∀ᵐ omega ∂mu,
        @condExp Omega Real (X.coordinateSquareConditioningSigma label)
            (m₀ := mOmega) _ _ mu
          ((cookBadEvent (X.squareRestriction label) profile D
              (cook.beta L)).indicator (fun _ => (1 : Real))) omega ≤
            cookFailureBound (cook.cookC L) (cook.cookc L) n := by
  exact cook.conditional mu (X.squareRestriction label) profile L
    (X.coordinateSquareFreshSigma label)
    (X.coordinateSquareConditioningSigma label)
    (X.coordinateSquareFreshSigma_le label)
    (X.coordinateSquareConditioningSigma_le label)
    D hsubgaussian hprofile hn hL
    (X.coordinateSquare_atom_measurable label)
    hDmeas
    (X.coordinateSquareFresh_indep_conditioning label)
    hDnorm

end BernoulliSection9
