import BernoulliSection9.ExternalInputs

/-!
# Canonical fresh/complement sigma-fields

For a finite iid family, this module constructs the sigma-field generated by
any selected set of coordinates.  Disjoint coordinate sets generate
independent sigma-fields.  In particular, a Cook square is independent of the
sigma-field generated by every coordinate outside that square.  The
construction is internal: callers do not supply an independence certificate.
-/

open scoped ProbabilityTheory

noncomputable section

namespace BernoulliSection9

open MeasureTheory ProbabilityTheory

/-- The tuple of iid coordinates indexed by a finite set. -/
def IidSubgaussianFamily.coordinateTuple
    {Omega iota : Type*} [MeasurableSpace Omega]
    {mu : Measure Omega} (S : IidSubgaussianFamily Omega mu iota)
    (U : Finset iota) : Omega -> (U -> Real) :=
  fun omega i => S.atom i omega

/-- The sigma-field generated by a finite set of iid coordinates. -/
def IidSubgaussianFamily.coordinateSigma
    {Omega iota : Type*} [MeasurableSpace Omega]
    {mu : Measure Omega} (S : IidSubgaussianFamily Omega mu iota)
    (U : Finset iota) : MeasurableSpace Omega :=
  MeasurableSpace.comap (S.coordinateTuple U) inferInstance

/-- The coordinate tuple is measurable for the ambient sigma-field. -/
theorem IidSubgaussianFamily.coordinateTuple_measurable
    {Omega iota : Type*} [mOmega : MeasurableSpace Omega]
    {mu : Measure Omega} (S : IidSubgaussianFamily Omega mu iota)
    (U : Finset iota) :
    @Measurable Omega (U -> Real) mOmega _ (S.coordinateTuple U) := by
  exact measurable_pi_lambda _ (fun i => S.measurable_atom i)

/-- The generated coordinate sigma-field is contained in the ambient one. -/
theorem IidSubgaussianFamily.coordinateSigma_le
    {Omega iota : Type*} [mOmega : MeasurableSpace Omega]
    {mu : Measure Omega} (S : IidSubgaussianFamily Omega mu iota)
    (U : Finset iota) : S.coordinateSigma U <= mOmega := by
  exact Measurable.comap_le (S.coordinateTuple_measurable U)

/-- Each selected atom is measurable for the sigma-field generated by the
selected tuple. -/
theorem IidSubgaussianFamily.atom_measurable_coordinateSigma
    {Omega iota : Type*} [mOmega : MeasurableSpace Omega]
    {mu : Measure Omega} (S : IidSubgaussianFamily Omega mu iota)
    (U : Finset iota) (i : U) :
    @Measurable Omega Real (S.coordinateSigma U) _ (S.atom i) := by
  have htuple :
      @Measurable Omega (U -> Real) (S.coordinateSigma U) _
        (S.coordinateTuple U) :=
    Measurable.of_comap_le le_rfl
  simpa [IidSubgaussianFamily.coordinateTuple, Function.comp_def] using
    (measurable_pi_apply i).comp htuple

/-- Disjoint coordinate sets generate independent sigma-fields. -/
theorem IidSubgaussianFamily.coordinateSigma_indep_of_disjoint
    {Omega iota : Type*} [mOmega : MeasurableSpace Omega]
    {mu : Measure Omega} (S : IidSubgaussianFamily Omega mu iota)
    (U V : Finset iota) (hUV : Disjoint U V) :
    Indep (S.coordinateSigma U) (S.coordinateSigma V) mu := by
  exact S.independent.indepFun_finset U V hUV S.measurable_atom

/-- A selected set of coordinates is independent of all remaining
coordinates. -/
theorem IidSubgaussianFamily.coordinateSigma_indep_complement
    {Omega iota : Type*} [mOmega : MeasurableSpace Omega]
    {mu : Measure Omega} [Fintype iota] [DecidableEq iota]
    (S : IidSubgaussianFamily Omega mu iota) (U : Finset iota) :
    Indep (S.coordinateSigma U)
      (S.coordinateSigma (Finset.univ \ U)) mu := by
  exact S.coordinateSigma_indep_of_disjoint U (Finset.univ \ U)
    Finset.disjoint_sdiff

/-- The finite image of an injectively labelled family. -/
def selectedCoordinateSet {iota kappa : Type*} [Fintype kappa]
    [DecidableEq iota] (label : kappa ↪ iota) : Finset iota :=
  Finset.univ.map label

/-- An atom obtained by injective reindexing is measurable for the
sigma-field generated by the selected image. -/
theorem IidSubgaussianFamily.reindexed_atom_measurable_selectedSigma
    {Omega iota kappa : Type*} [mOmega : MeasurableSpace Omega]
    {mu : Measure Omega} [Fintype kappa] [DecidableEq iota]
    (S : IidSubgaussianFamily Omega mu iota) (label : kappa ↪ iota)
    (k : kappa) :
    @Measurable Omega Real
      (S.coordinateSigma (selectedCoordinateSet label)) _
      ((S.reindex label).atom k) := by
  let i : selectedCoordinateSet label :=
    ⟨label k, by simp [selectedCoordinateSet]⟩
  simpa [IidSubgaussianFamily.reindex] using
    S.atom_measurable_coordinateSigma (selectedCoordinateSet label) i

/-- The selected image of an injection is independent of its full finite
coordinate complement. -/
theorem IidSubgaussianFamily.selectedSigma_indep_complement
    {Omega iota kappa : Type*} [mOmega : MeasurableSpace Omega]
    {mu : Measure Omega} [Fintype iota] [Fintype kappa]
    [DecidableEq iota]
    (S : IidSubgaussianFamily Omega mu iota) (label : kappa ↪ iota) :
    Indep (S.coordinateSigma (selectedCoordinateSet label))
      (S.coordinateSigma (Finset.univ \ selectedCoordinateSet label)) mu :=
  S.coordinateSigma_indep_complement (selectedCoordinateSet label)

end BernoulliSection9
