import BernoulliSection9.ConditionalUniformLift
import BernoulliSection9.TerminalConcretePublic
import BernoulliLinearAlgebra.PolynomialCoefficientContinuity
import Mathlib.MeasureTheory.Function.ConditionalExpectation.Real

/-!
# The terminal estimate with an outside-measurable random outer matrix

The concrete terminal theorem is uniform in every deterministic outer
matrix `Q`.  This file supplies the measure-theoretic passage to an
outer matrix which is measurable with respect to an outside sigma-field and
is independent of the full fresh packet vector.

The sigma-field, measurability of `Q`, and independence from the fresh vector
are explicit in the final theorem signature.  The main package states
Parseval fiberwise against the law of the fresh vector, so it needs no moment
assumption on an arbitrary random `Q`.  A separate corollary turns that
fiberwise identity into a Bochner conditional-expectation identity when the
random second moment is integrable.  (The capped loss and the two conditional
probability bounds need no moment assumption, because their integrands are
bounded.)
-/

open scoped ProbabilityTheory Matrix.Norms.L2Operator

noncomputable section

/- The joint finite-dimensional determinant continuity term is large after
all packet indices are unfolded.  Its kernel reduction exceeds the default
heartbeat budget even though the proof is a direct continuity composition. -/
set_option maxHeartbeats 1000000

namespace BernoulliSection9

open MeasureTheory ProbabilityTheory BernoulliLinearAlgebra

universe u v w z

/-! ## Conditioning on an abstract sub-sigma-field -/

/-- A type-level copy of `Omega` carrying a specified measurable space.
It lets us apply the regular-conditional-distribution theorem to the identity
map into an outside sigma-field, without requiring that sigma-field to be
generated by one of the paper's matrix-valued random variables. -/
structure SigmaCopy (Omega : Type u) (_m : MeasurableSpace Omega) where
  val : Omega

namespace SigmaCopy

variable {Omega : Type u} {m : MeasurableSpace Omega}

def up (omega : Omega) : SigmaCopy Omega m := ⟨omega⟩

def down (omega : SigmaCopy Omega m) : Omega := omega.val

@[simp] theorem down_up (omega : Omega) :
    down (up (m := m) omega) = omega := rfl

@[simp] theorem up_down (omega : SigmaCopy Omega m) :
    up (m := m) (down omega) = omega := by
  cases omega
  rfl

instance : MeasurableSpace (SigmaCopy Omega m) :=
  MeasurableSpace.map (up (m := m)) m

theorem measurable_up :
    @Measurable Omega (SigmaCopy Omega m) m inferInstance (up (m := m)) := by
  rw [measurable_iff_le_map]
  exact le_rfl

theorem measurable_down :
    @Measurable (SigmaCopy Omega m) Omega inferInstance m down := by
  rw [measurable_iff_le_map]
  change m <= (m.map (up (m := m))).map down
  rw [MeasurableSpace.map_comp]
  have hcomp : down ∘ up (m := m) = id := by
    funext omega
    simp
  rw [hcomp, MeasurableSpace.map_id]

/-- The identity into `SigmaCopy Omega m` generates exactly `m`. -/
theorem comap_up :
    MeasurableSpace.comap (up (m := m)) inferInstance = m := by
  apply MeasurableSpace.ext
  intro s
  constructor
  · rintro ⟨t, ht, rfl⟩
    exact ht
  · intro hs
    have heq : (up (m := m)) ⁻¹' (down ⁻¹' s) = s := by
      ext omega
      simp
    refine ⟨down ⁻¹' s, ?_, heq⟩
    · change MeasurableSet[m] ((up (m := m)) ⁻¹' (down ⁻¹' s))
      rw [heq]
      exact hs

end SigmaCopy

/-- Conditional Fubini with conditioning on an explicitly supplied outside
sigma-field.  This is the abstract-sigma-field form of
`condExp_parameterized_ae_eq_integral_map_of_indepFun`.

The proof views the identity map into a copy of `Omega` equipped with
`mOutside` as the outside random parameter. -/
theorem condExp_parameterized_ae_eq_integral_map_of_indepSigma
    {Omega : Type u} {Param : Type v} {Fresh : Type w} {E : Type z}
    [mOmega : MeasurableSpace Omega] [MeasurableSpace Param]
    [MeasurableSpace Fresh] [StandardBorelSpace Fresh] [Nonempty Fresh]
    [NormedAddCommGroup E] [NormedSpace Real E] [CompleteSpace E]
    (mu : Measure Omega) [IsProbabilityMeasure mu]
    (mOutside : MeasurableSpace Omega) (hmOutside : mOutside <= mOmega)
    (Q : Omega -> Param) (X : Omega -> Fresh)
    (hQ : @Measurable Omega Param mOutside inferInstance Q)
    (hX : AEMeasurable X mu)
    (h_indep : Indep mOutside
      (MeasurableSpace.comap X inferInstance) mu)
    (f : Param × Fresh -> E) (hf : StronglyMeasurable f)
    (hf_int : Integrable (fun omega => f (Q omega, X omega)) mu) :
    mu[fun omega => f (Q omega, X omega) | mOutside] =ᵐ[mu]
      fun omega => ∫ x, f (Q omega, x)
        ∂(@Measure.map Omega Fresh mOmega inferInstance X mu) := by
  letI : MeasurableSpace Omega := mOmega
  let outside : Omega -> SigmaCopy Omega mOutside :=
    SigmaCopy.up (m := mOutside)
  let fOutside : SigmaCopy Omega mOutside × Fresh -> E :=
    fun p => f (Q (SigmaCopy.down p.1), p.2)
  have houtside : @Measurable Omega (SigmaCopy Omega mOutside)
      mOmega inferInstance outside :=
    SigmaCopy.measurable_up.mono hmOutside le_rfl
  have hQcopy : @Measurable (SigmaCopy Omega mOutside) Param
      inferInstance inferInstance (fun q => Q (SigmaCopy.down q)) :=
    hQ.comp SigmaCopy.measurable_down
  have hfOutside : StronglyMeasurable fOutside := by
    apply hf.comp_measurable
    exact (hQcopy.comp measurable_fst).prodMk measurable_snd
  have h_indepFun : IndepFun outside X mu := by
    rw [IndepFun_iff_Indep]
    simpa [outside, SigmaCopy.comap_up] using h_indep
  have hOutsideInt :
      Integrable (fun omega => fOutside (outside omega, X omega)) mu := by
    simpa [outside, fOutside] using hf_int
  have heq := condExp_parameterized_ae_eq_integral_map_of_indepFun
    mu outside X houtside hX h_indepFun fOutside hfOutside hOutsideInt
  simpa [outside, fOutside, SigmaCopy.comap_up] using heq

namespace TerminalAssembly

local instance packetMatrixMeasurableSpace {w : Type*} :
    MeasurableSpace (Matrix (PacketOuter w) (PacketOuter w) Complex) :=
  borel _

local instance packetMatrixBorelSpace {w : Type*} :
    BorelSpace (Matrix (PacketOuter w) (PacketOuter w) Complex) :=
  ⟨rfl⟩

/-! ## Joint Borel measurability of the literal terminal polynomial -/

/-- The literal terminal determinant evaluated at a deterministic vector of
fresh real entries. -/
def packetTerminalValueFromSample
    {w : Type*} [Fintype w] [DecidableEq w]
    (Q : Matrix (PacketOuter w) (PacketOuter w) Complex)
    (z : Complex) (x : ThreeBlockVariable w -> Real) : Complex :=
  (threeBlockH (threeBlockOuterOfPacket Q) z
    (fun i => (x i : Complex))).det

/-- The full fresh packet vector as one finite-dimensional random variable. -/
def packetFreshSample
    {Omega w : Type*} [MeasurableSpace Omega]
    [Fintype w] [DecidableEq w] {mu : Measure Omega}
    (X : IidSubgaussianFamily Omega mu (ThreeBlockVariable w)) :
    Omega -> (ThreeBlockVariable w -> Real) :=
  fun omega i => X.atom i omega

theorem measurable_packetFreshSample
    {Omega w : Type*} [MeasurableSpace Omega]
    [Fintype w] [DecidableEq w] {mu : Measure Omega}
    (X : IidSubgaussianFamily Omega mu (ThreeBlockVariable w)) :
    Measurable (packetFreshSample X) := by
  exact measurable_pi_lambda _ (fun i => X.measurable_atom i)

@[simp] theorem packetTerminalValueFromSample_packetFreshSample
    {Omega w : Type*} [MeasurableSpace Omega]
    [Fintype w] [DecidableEq w] {mu : Measure Omega}
    (Q : Matrix (PacketOuter w) (PacketOuter w) Complex)
    (z : Complex)
    (X : IidSubgaussianFamily Omega mu (ThreeBlockVariable w))
    (omega : Omega) :
    packetTerminalValueFromSample Q z (packetFreshSample X omega) =
      packetTerminalValue Q z X omega := rfl

/-- Joint continuity of the literal determinant in the outer matrix and all
fresh entries. -/
theorem continuous_packetTerminalValueFromSample
    {w : Type*} [Fintype w] [DecidableEq w] (z : Complex) :
    Continuous (fun p :
      Matrix (PacketOuter w) (PacketOuter w) Complex ×
        (ThreeBlockVariable w -> Real) =>
      packetTerminalValueFromSample p.1 z p.2) := by
  unfold packetTerminalValueFromSample
  apply Continuous.matrix_det
  apply continuous_matrix
  intro i j
  have hdelta : Continuous (fun p :
      Matrix (PacketOuter w) (PacketOuter w) Complex ×
        (ThreeBlockVariable w -> Real) =>
      threeBlockDelta (fun k => (p.2 k : Complex)) i j) := by
    unfold threeBlockDelta
    split_ifs <;> fun_prop
  have hemb : Continuous (fun p :
      Matrix (PacketOuter w) (PacketOuter w) Complex ×
        (ThreeBlockVariable w -> Real) =>
      threeBlockEmb (threeBlockOuterOfPacket p.1) i j) := by
    rcases i with i | i
    · rcases j with j | j
      · simp only [threeBlockEmb_outer, threeBlockOuterOfPacket,
          Matrix.submatrix_apply]
        fun_prop
      · simp only [threeBlockEmb_center_col]
        fun_prop
    · simp only [threeBlockEmb_center_row]
      fun_prop
  change Continuous
    ((fun p : Matrix (PacketOuter w) (PacketOuter w) Complex ×
        (ThreeBlockVariable w -> Real) =>
        threeBlockDelta (fun k => (p.2 k : Complex)) i j) -
      (fun _ => z • if i = j then 1 else 0) +
      fun p => threeBlockEmb (threeBlockOuterOfPacket p.1) i j)
  exact (hdelta.sub continuous_const).add hemb

/-- Every entry of the polynomial terminal matrix is coefficientwise
continuous in the outer matrix. -/
theorem coeffwiseContinuous_packetTerminalHPolynomial_entry
    {w : Type*} [Fintype w] [DecidableEq w] (z : Complex)
    (i j : ThreeBlockIndex w) :
    CoeffwiseContinuous fun Q :
        Matrix (PacketOuter w) (PacketOuter w) Complex =>
      threeBlockHPolynomial (threeBlockOuterOfPacket Q) z i j := by
  have hentry : Continuous fun Q :
      Matrix (PacketOuter w) (PacketOuter w) Complex =>
      threeBlockEmb (threeBlockOuterOfPacket Q) i j := by
    rcases i with i | i
    · rcases j with j | j
      · simp only [threeBlockEmb_outer, threeBlockOuterOfPacket,
          Matrix.submatrix_apply]
        fun_prop
      · simp only [threeBlockEmb_center_col]
        fun_prop
    · simp only [threeBlockEmb_center_row]
      fun_prop
  have hbase : CoeffwiseContinuous fun _Q :
      Matrix (PacketOuter w) (PacketOuter w) Complex =>
      threeBlockDeltaPolynomial i j -
        (MvPolynomial.C z : MvPolynomial (ThreeBlockVariable w) Complex) *
          (1 : Matrix (ThreeBlockIndex w) (ThreeBlockIndex w)
            (MvPolynomial (ThreeBlockVariable w) Complex)) i j :=
    CoeffwiseContinuous.const _
  have hemb : CoeffwiseContinuous fun Q :
      Matrix (PacketOuter w) (PacketOuter w) Complex =>
      MvPolynomial.C (σ := ThreeBlockVariable w)
        (threeBlockEmb (threeBlockOuterOfPacket Q) i j) :=
    CoeffwiseContinuous.C (v := ThreeBlockVariable w) hentry
  simpa [threeBlockHPolynomial] using hbase.add hemb

theorem coeffwiseContinuous_packetTerminalDetPolynomial
    {w : Type*} [Fintype w] [DecidableEq w] (z : Complex) :
    CoeffwiseContinuous fun Q :
        Matrix (PacketOuter w) (PacketOuter w) Complex =>
      threeBlockDetPolynomial (threeBlockOuterOfPacket Q) z := by
  apply coeffwiseContinuous_det
  exact coeffwiseContinuous_packetTerminalHPolynomial_entry z

/-- The complete squarefree coefficient norm is a continuous, hence Borel,
function of `Q`. -/
theorem continuous_packetTerminalCoefficientNorm
    {w : Type*} [Fintype w] [DecidableEq w] (z : Complex) :
    Continuous (fun Q : Matrix (PacketOuter w) (PacketOuter w) Complex =>
      packetTerminalCoefficientNorm Q z) := by
  change Continuous (fun Q :
      Matrix (PacketOuter w) (PacketOuter w) Complex =>
    ‖(WithLp.toLp 2 (fun S : Finset (ThreeBlockVariable w) =>
      MvPolynomial.coeff (squarefreeExponent S)
        (threeBlockDetPolynomial (threeBlockOuterOfPacket Q) z)) :
      CoeffSpace (ThreeBlockVariable w))‖)
  exact (coeffwiseContinuous_packetTerminalDetPolynomial
    (w := w) z).continuous_selectedCoeffNorm squarefreeExponent _

def packetTerminalCappedLoss
    {w : Type*} [Fintype w] [DecidableEq w]
    (T : Real) (z : Complex)
    (p : Matrix (PacketOuter w) (PacketOuter w) Complex ×
      (ThreeBlockVariable w -> Real)) : Real :=
  cappedLogLoss T (packetTerminalCoefficientNorm p.1 z)
    (packetTerminalValueFromSample p.1 z p.2)

def packetTerminalZeroIndicator
    {w : Type*} [Fintype w] [DecidableEq w]
    (z : Complex)
    (p : Matrix (PacketOuter w) (PacketOuter w) Complex ×
      (ThreeBlockVariable w -> Real)) : Real :=
  if packetTerminalValueFromSample p.1 z p.2 = 0 then 1 else 0

def packetTerminalSecondMoment
    {w : Type*} [Fintype w] [DecidableEq w]
    (z : Complex)
    (p : Matrix (PacketOuter w) (PacketOuter w) Complex ×
      (ThreeBlockVariable w -> Real)) : Real :=
  norm (packetTerminalValueFromSample p.1 z p.2) ^ 2

theorem measurable_packetTerminalCappedLoss
    {w : Type*} [Fintype w] [DecidableEq w]
    (T : Real) (z : Complex) :
    Measurable (packetTerminalCappedLoss (w := w) T z) := by
  unfold packetTerminalCappedLoss cappedLogLoss
  have hvalue := (continuous_packetTerminalValueFromSample
    (w := w) z).measurable
  have hcoefficient : Measurable
      (fun p : Matrix (PacketOuter w) (PacketOuter w) Complex ×
        (ThreeBlockVariable w -> Real) =>
        packetTerminalCoefficientNorm p.1 z) :=
    (continuous_packetTerminalCoefficientNorm
      (w := w) z).measurable.comp measurable_fst
  apply Measurable.ite
  · exact hvalue (measurableSet_singleton 0)
  · exact measurable_const
  · exact Measurable.min measurable_const
      (Real.continuous_posLog.measurable.comp
        (hcoefficient.div hvalue.norm))

theorem measurable_packetTerminalZeroIndicator
    {w : Type*} [Fintype w] [DecidableEq w] (z : Complex) :
    Measurable (packetTerminalZeroIndicator (w := w) z) := by
  unfold packetTerminalZeroIndicator
  apply Measurable.ite
  · exact (continuous_packetTerminalValueFromSample
      (w := w) z).measurable (measurableSet_singleton 0)
  · exact measurable_const
  · exact measurable_const

theorem measurable_packetTerminalSecondMoment
    {w : Type*} [Fintype w] [DecidableEq w] (z : Complex) :
    Measurable (packetTerminalSecondMoment (w := w) z) := by
  exact (continuous_packetTerminalValueFromSample
    (w := w) z).measurable.norm.pow_const 2

/-! ## The reverse event as a function of the fresh vector -/

def packetReverseFailureIndicator
    {w : Type*} [Fintype w]
    (M : Real) (x : ThreeBlockVariable w -> Real) : Real := by
  classical
  exact if (forall i, abs (x i) <= M) then 0 else 1

theorem measurableSet_packetSampleBounded
    {w : Type*} [Fintype w] (M : Real) :
    MeasurableSet {x : ThreeBlockVariable w -> Real |
      forall i, abs (x i) <= M} := by
  rw [show {x : ThreeBlockVariable w -> Real |
      forall i, abs (x i) <= M} =
      ⋂ i, {x : ThreeBlockVariable w -> Real | abs (x i) <= M} by
    ext x
    simp]
  apply MeasurableSet.iInter
  intro i
  exact measurableSet_le (measurable_pi_apply i).abs measurable_const

theorem measurable_packetReverseFailureIndicator
    {w : Type*} [Fintype w] (M : Real) :
    Measurable (packetReverseFailureIndicator (w := w) M) := by
  classical
  unfold packetReverseFailureIndicator
  apply Measurable.ite (measurableSet_packetSampleBounded M)
  · exact measurable_const
  · exact measurable_const

theorem packetReverseFailureIndicator_packetFreshSample
    {Omega w : Type*} [MeasurableSpace Omega]
    [Fintype w] [DecidableEq w] {mu : Measure Omega}
    (X : IidSubgaussianFamily Omega mu (ThreeBlockVariable w))
    (M : Real) (omega : Omega) :
    packetReverseFailureIndicator M (packetFreshSample X omega) =
      (coordinatewiseBoundedEvent X M)ᶜ.indicator (fun _ => (1 : Real)) omega := by
  classical
  by_cases hm : omega ∈ coordinatewiseBoundedEvent X M
  · have hsample : forall i,
    abs (packetFreshSample X omega i) <= M := by
      simpa only [coordinatewiseBoundedEvent, Set.mem_setOf_eq,
        packetFreshSample] using hm
    rw [show packetReverseFailureIndicator M (packetFreshSample X omega) = 0 by
      simp only [packetReverseFailureIndicator, if_pos hsample]]
    simp [hm]
  · have hsample : ¬ forall i,
    abs (packetFreshSample X omega i) <= M := by
      simpa only [coordinatewiseBoundedEvent, Set.mem_setOf_eq,
        packetFreshSample] using hm
    rw [show packetReverseFailureIndicator M (packetFreshSample X omega) = 1 by
      simp only [packetReverseFailureIndicator, if_neg hsample]]
    simp [hm]

/-! ## Conditional terminal conclusion -/

/-- A non-typeclass carrier for the outside sigma-field.  Keeping this
wrapper in the result object prevents the outside space from accidentally
replacing the ambient measurable space during typeclass search. -/
structure OutsideSigmaField (Omega : Type u) where
  space : MeasurableSpace Omega

/-- The conditional analogue of the fixed-`Q` terminal package.  Conditional
probabilities are represented as conditional expectations of their `0/1`
indicators. -/
structure PacketTerminalRandomQConditionalResult
    {Omega : Type u} [mOmega : MeasurableSpace Omega]
    (outside : OutsideSigmaField Omega)
    (mu : Measure Omega)
    (W : Nat) (z : Complex)
    (X : IidSubgaussianFamily Omega mu (ThreeBlockVariable (Fin W)))
    (Q : Omega -> Matrix (PacketOuter (Fin W)) (PacketOuter (Fin W)) Complex)
    (baseLoss badProbability maxEventRate : Real) where
  coefficientNorm_pos : forall omega,
    0 < packetTerminalCoefficientNorm (Q omega) z
  coefficientNorm_stronglyMeasurable : StronglyMeasurable
    (fun omega => packetTerminalCoefficientNorm (Q omega) z)
  value_stronglyMeasurable : StronglyMeasurable
    (fun omega => packetTerminalValue (Q omega) z X omega)
  capped : forall T : Real, 0 < T ->
    ∀ᵐ omega ∂mu,
      mu[fun eta => cappedLogLoss T
          (packetTerminalCoefficientNorm (Q eta) z)
          (packetTerminalValue (Q eta) z X eta) | outside.space] omega <=
        baseLoss + badProbability * T
  zero_probability : ∀ᵐ omega ∂mu,
    mu[fun eta => if packetTerminalValue (Q eta) z X eta = 0
        then (1 : Real) else 0 | outside.space] omega <= badProbability
  reverse : forall omega,
    omega ∈ coordinatewiseBoundedEvent X
      (packetCoordinateMaxThreshold X maxEventRate) ->
      Real.posLog
        (norm (packetTerminalValue (Q omega) z X omega) /
          packetTerminalCoefficientNorm (Q omega) z) <= baseLoss
  reverse_event_compl_probability : ∀ᵐ omega ∂mu,
    mu[fun eta =>
      (coordinatewiseBoundedEvent X
        (packetCoordinateMaxThreshold X maxEventRate))ᶜ.indicator
          (fun _ => (1 : Real)) eta | outside.space] omega <=
      Real.exp (-maxEventRate)
  parseval_fiber : forall omega,
    packetTerminalCoefficientNorm (Q omega) z ^ 2 =
      ∫ x, norm (packetTerminalValueFromSample (Q omega) z x) ^ 2
        ∂(@Measure.map Omega (ThreeBlockVariable (Fin W) -> Real)
          mOmega inferInstance (packetFreshSample X) mu)

section RandomQConditionalTheorems

variable {Omega : Type u} [mOmega : MeasurableSpace Omega]

/-- The concrete fixed-`Q` theorem lifted to an outside-measurable random
`Q`.  No RRQR, mask, elimination, or square-selection certificate occurs in
the signature.

The Parseval field is deliberately stated fiberwise.  Consequently this main
theorem has no extra moment hypothesis beyond the paper's assumptions. -/
noncomputable def packetTerminalRandomQConditionalResult
    (cook : CookDeformedSquareInput.{u, u})
    (mu : Measure Omega) [IsProbabilityMeasure mu]
    {W : Nat} (Kz : Nat) (z : Complex)
    (X : IidSubgaussianFamily Omega mu (ThreeBlockVariable (Fin W)))
    (t : Real)
    (hnum : PacketTerminalCanonicalLargeWConditions cook z X Kz t)
    (mOutside : MeasurableSpace Omega)
    (hmOutside : mOutside <= mOmega)
    (Q : Omega -> Matrix (PacketOuter (Fin W)) (PacketOuter (Fin W)) Complex)
    (hQ : @Measurable Omega
      (Matrix (PacketOuter (Fin W)) (PacketOuter (Fin W)) Complex)
      mOutside inferInstance Q)
    (h_indep : @Indep Omega mOutside
      (MeasurableSpace.comap
        (@packetFreshSample Omega (Fin W) mOmega inferInstance inferInstance
          mu X) inferInstance) mOmega mu) :
    @PacketTerminalRandomQConditionalResult Omega mOmega ⟨mOutside⟩ mu W z X Q
      (@terminalUniformBaseLoss Omega mOmega mu W cook Kz z X t)
      (terminalUniformBadProbability cook W Kz t) t := by
  letI : MeasurableSpace Omega := mOmega
  let fresh := packetFreshSample X
  let fixed : PacketTerminalConcreteConclusion cook mu W Kz z X t :=
    packetTerminalConcreteConclusion cook mu Kz z X t hnum
  have hfresh : Measurable fresh := measurable_packetFreshSample X
  have hQOutside : @Measurable Omega
      (Matrix (PacketOuter (Fin W)) (PacketOuter (Fin W)) Complex)
      mOutside inferInstance Q := hQ
  have hQAmbient : Measurable Q := hQ.mono hmOutside le_rfl
  have hpair : Measurable (fun omega => (Q omega, fresh omega)) :=
    hQAmbient.prodMk hfresh
  have hvalueMeas : Measurable
      (fun omega => packetTerminalValue (Q omega) z X omega) := by
    change Measurable (fun omega =>
      packetTerminalValueFromSample (Q omega) z (fresh omega))
    exact (continuous_packetTerminalValueFromSample
      (w := Fin W) z).measurable.comp hpair
  have hcoefficientStrong : StronglyMeasurable
      (fun omega => packetTerminalCoefficientNorm (Q omega) z) :=
    ((continuous_packetTerminalCoefficientNorm
      (w := Fin W) z).measurable.comp hQAmbient).stronglyMeasurable
  have hvalueStrong : StronglyMeasurable
      (fun omega => packetTerminalValue (Q omega) z X omega) :=
    hvalueMeas.stronglyMeasurable
  refine
    { coefficientNorm_pos := fun omega =>
        packetTerminalCoefficientNorm_pos (Q omega) z
      coefficientNorm_stronglyMeasurable := hcoefficientStrong
      value_stronglyMeasurable := hvalueStrong
      capped := ?_
      zero_probability := ?_
      reverse := ?_
      reverse_event_compl_probability := ?_
      parseval_fiber := ?_ }
  · intro T hT
    let loss := packetTerminalCappedLoss (w := Fin W) T z
    have hloss : StronglyMeasurable loss :=
      (measurable_packetTerminalCappedLoss (w := Fin W) T z).stronglyMeasurable
    have hlossRandom : Integrable
        (fun omega => loss (Q omega, fresh omega)) mu := by
      apply (integrable_const T).mono'
      · exact (hloss.comp_measurable hpair).aestronglyMeasurable
      · filter_upwards [] with omega
        dsimp [loss, packetTerminalCappedLoss]
        rw [abs_of_nonneg (cappedLogLoss_nonneg hT.le)]
        exact cappedLogLoss_le_cap
    have heq := condExp_parameterized_ae_eq_integral_map_of_indepSigma
      mu mOutside hmOutside Q fresh hQOutside hfresh.aemeasurable h_indep
      loss hloss hlossRandom
    filter_upwards [heq] with omega homega
    change mu[fun eta => loss (Q eta, fresh eta) | mOutside] omega <= _
    rw [homega]
    rw [integral_map hfresh.aemeasurable]
    · simpa [loss, packetTerminalCappedLoss, fresh] using
        (fixed (Q omega)).conclusion.capped T hT
    · exact (hloss.comp_measurable
        (measurable_const.prodMk measurable_id)).aestronglyMeasurable
  · let zeroIndicator := packetTerminalZeroIndicator (w := Fin W) z
    have hzero : StronglyMeasurable zeroIndicator :=
      (measurable_packetTerminalZeroIndicator (w := Fin W) z).stronglyMeasurable
    have hzeroRandom : Integrable
        (fun omega => zeroIndicator (Q omega, fresh omega)) mu := by
      apply (integrable_const (1 : Real)).mono'
      · exact (hzero.comp_measurable hpair).aestronglyMeasurable
      · filter_upwards [] with omega
        dsimp [zeroIndicator, packetTerminalZeroIndicator]
        split_ifs <;> norm_num
    have heq := condExp_parameterized_ae_eq_integral_map_of_indepSigma
      mu mOutside hmOutside Q fresh hQOutside hfresh.aemeasurable h_indep
      zeroIndicator hzero hzeroRandom
    filter_upwards [heq] with omega homega
    change mu[fun eta => zeroIndicator (Q eta, fresh eta) | mOutside] omega <= _
    rw [homega]
    rw [integral_map hfresh.aemeasurable]
    · let zeroSet : Set Omega :=
        {eta | packetTerminalValue (Q omega) z X eta = 0}
      have hzeroSet : MeasurableSet zeroSet :=
        (measurable_packetTerminalValue (Q omega) z X)
          (measurableSet_singleton 0)
      have hintegral :
          (∫ eta, zeroIndicator (Q omega, fresh eta) ∂mu) =
            mu.real zeroSet := by
        have hfun : (fun eta => zeroIndicator (Q omega, fresh eta)) =
            zeroSet.indicator (fun _ => (1 : Real)) := by
          funext eta
          by_cases heta : packetTerminalValue (Q omega) z X eta = 0
          · simp [zeroIndicator, packetTerminalZeroIndicator, zeroSet,
              fresh, heta]
          · simp [zeroIndicator, packetTerminalZeroIndicator, zeroSet,
              fresh, heta]
        rw [hfun]
        simpa using (integral_indicator_const
          (μ := mu) (1 : Real) hzeroSet)
      rw [hintegral]
      exact (fixed (Q omega)).conclusion.zero_probability
    · exact (hzero.comp_measurable
        (measurable_const.prodMk measurable_id)).aestronglyMeasurable
  · intro omega homega
    have C := fixed (Q omega)
    apply C.conclusion.reverse omega
    rw [C.reverse_event_eq]
    exact homega
  · let M := packetCoordinateMaxThreshold X t
    let failure := fun p :
        Matrix (PacketOuter (Fin W)) (PacketOuter (Fin W)) Complex ×
          (ThreeBlockVariable (Fin W) -> Real) =>
      packetReverseFailureIndicator M p.2
    have hfailure : StronglyMeasurable failure := by
      exact (measurable_packetReverseFailureIndicator
        (w := Fin W) M).stronglyMeasurable.comp_measurable measurable_snd
    have hfailureRandom : Integrable
        (fun omega => failure (Q omega, fresh omega)) mu := by
      apply (integrable_const (1 : Real)).mono'
      · exact (hfailure.comp_measurable hpair).aestronglyMeasurable
      · filter_upwards [] with omega
        dsimp [failure, packetReverseFailureIndicator]
        split_ifs <;> norm_num
    have heq := condExp_parameterized_ae_eq_integral_map_of_indepSigma
      mu mOutside hmOutside Q fresh hQOutside hfresh.aemeasurable h_indep
      failure hfailure hfailureRandom
    filter_upwards [heq] with omega homega
    have hfailureEq :
        (fun eta => failure (Q eta, fresh eta)) =
          fun eta =>
            (coordinatewiseBoundedEvent X M)ᶜ.indicator
              (fun _ => (1 : Real)) eta := by
      funext eta
      exact packetReverseFailureIndicator_packetFreshSample X M eta
    rw [← hfailureEq]
    rw [homega]
    rw [integral_map hfresh.aemeasurable]
    · have C := fixed (Q omega)
      have hmeasEvent : MeasurableSet (coordinatewiseBoundedEvent X M) := by
        exact measurableSet_coordinatewiseBoundedEvent X M
      have hintegral :
          (∫ eta, failure (Q omega, fresh eta) ∂mu) =
            mu.real (coordinatewiseBoundedEvent X M)ᶜ := by
        have hfun : (fun eta => failure (Q omega, fresh eta)) =
            (coordinatewiseBoundedEvent X M)ᶜ.indicator
              (fun _ => (1 : Real)) := by
          funext eta
          exact packetReverseFailureIndicator_packetFreshSample X M eta
        rw [hfun]
        simpa using (integral_indicator_const
          (μ := mu) (1 : Real) hmeasEvent.compl)
      rw [hintegral]
      simpa [M, C.reverse_event_eq] using C.reverse_event_compl_probability
    · exact (hfailure.comp_measurable
        (measurable_const.prodMk measurable_id)).aestronglyMeasurable
  · intro omega
    rw [integral_map hfresh.aemeasurable]
    · simpa [fresh] using packetTerminal_parseval mu (Q omega) z X
    · exact ((measurable_packetTerminalSecondMoment
        (w := Fin W) z).stronglyMeasurable.comp_measurable
        (measurable_const.prodMk measurable_id)).aestronglyMeasurable

/-- If the random second moment is integrable, fiberwise Parseval becomes an
exact conditional-expectation identity.  The integrability hypothesis is
separate from the caller-facing terminal package because Bochner conditional
expectation is defined to be zero on non-integrable functions. -/
theorem packetTerminalRandomQ_condExp_parseval
    (mu : Measure Omega) [IsProbabilityMeasure mu]
    {W : Nat} (z : Complex)
    (X : IidSubgaussianFamily Omega mu (ThreeBlockVariable (Fin W)))
    (Q : Omega -> Matrix (PacketOuter (Fin W)) (PacketOuter (Fin W)) Complex)
    (hsecondMoment : Integrable
      (fun omega => norm (packetTerminalValue (Q omega) z X omega) ^ 2) mu)
    (mOutside : MeasurableSpace Omega)
    (hmOutside : mOutside <= mOmega)
    (hQ : @Measurable Omega
      (Matrix (PacketOuter (Fin W)) (PacketOuter (Fin W)) Complex)
      mOutside inferInstance Q)
    (h_indep : @Indep Omega mOutside
      (MeasurableSpace.comap
        (@packetFreshSample Omega (Fin W) mOmega inferInstance inferInstance
          mu X) inferInstance) mOmega mu) :
    mu[fun eta => norm (@packetTerminalValue Omega (Fin W) mOmega
          inferInstance inferInstance mu (Q eta) z X eta) ^ 2 |
        mOutside] =ᵐ[mu]
      fun omega => packetTerminalCoefficientNorm (Q omega) z ^ 2 := by
  letI : MeasurableSpace Omega := mOmega
  let fresh := packetFreshSample X
  let second := packetTerminalSecondMoment (w := Fin W) z
  have hfresh : Measurable fresh := measurable_packetFreshSample X
  have hQOutside : @Measurable Omega
      (Matrix (PacketOuter (Fin W)) (PacketOuter (Fin W)) Complex)
      mOutside inferInstance Q := hQ
  have hsecond : StronglyMeasurable second :=
    (measurable_packetTerminalSecondMoment (w := Fin W) z).stronglyMeasurable
  have heq := condExp_parameterized_ae_eq_integral_map_of_indepSigma
    mu mOutside hmOutside Q fresh hQOutside hfresh.aemeasurable h_indep
    second hsecond (by simpa [second, packetTerminalSecondMoment, fresh]
      using hsecondMoment)
  refine heq.trans (ae_of_all mu fun omega => ?_)
  change (∫ x, second (Q omega, x) ∂Measure.map fresh mu) = _
  rw [integral_map hfresh.aemeasurable]
  · simpa [second, packetTerminalSecondMoment, fresh] using
      (packetTerminal_parseval mu (Q omega) z X).symm
  · exact (hsecond.comp_measurable
      (measurable_const.prodMk measurable_id)).aestronglyMeasurable

end RandomQConditionalTheorems

end TerminalAssembly

end BernoulliSection9
